### ISSUE TITLE
TypeError: 'str' object does not support item assignment

### ISSUE THREAD

**Issue by lurebgi** [EI-CoreBioinformatics/mikado#140]
Hi, I had an error when running the pick step

> mikado pick -p 1 --json-conf out.cfg.json --scoring-file amphioxus2.yaml --loci_out bj.out --mode permissive -l pick.log
> /home/user/luohao/anaconda2/envs/mikado/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
>   return f(*args, **kwds)
> /home/user/luohao/anaconda2/envs/mikado/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
>   return f(*args, **kwds)
> /home/user/luohao/anaconda2/envs/mikado/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
>   return f(*args, **kwds)
> /home/user/luohao/anaconda2/envs/mikado/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
>   return f(*args, **kwds)
> /home/user/luohao/anaconda2/envs/mikado/lib/python3.5/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
>   from numpy.core.umath_tests import inner1d
> 2018-10-31 08:04:39,832 - pick_init - configurator.py:567 - ERROR - check_json - MainProcess - 'str' object does not support item assignment
> Traceback (most recent call last):
>   File "/home/user/luohao/anaconda2/envs/mikado/lib/python3.5/site-packages/Mikado/configuration/configurator.py", line 519, in check_json
>     validator.validate(json_conf)
>   File "/home/user/luohao/anaconda2/envs/mikado/lib/python3.5/site-packages/jsonschema/validators.py", line 129, in validate
>     for error in self.iter_errors(*args, **kwargs):
>   File "/home/user/luohao/anaconda2/envs/mikado/lib/python3.5/site-packages/jsonschema/validators.py", line 105, in iter_errors
>     for error in errors:
>   File "/home/user/luohao/anaconda2/envs/mikado/lib/python3.5/site-packages/Mikado/configuration/configurator.py", line 100, in set_defaults
>     for error in validate_properties(validator, properties, instance, schema):
>   File "/home/user/luohao/anaconda2/envs/mikado/lib/python3.5/site-packages/jsonschema/_validators.py", line 304, in properties_draft4
>     schema_path=property,
>   File "/home/user/luohao/anaconda2/envs/mikado/lib/python3.5/site-packages/jsonschema/validators.py", line 121, in descend
>     for error in self.iter_errors(instance, schema):
>   File "/home/user/luohao/anaconda2/envs/mikado/lib/python3.5/site-packages/jsonschema/validators.py", line 105, in iter_errors
>     for error in errors:
>   File "/home/user/luohao/anaconda2/envs/mikado/lib/python3.5/site-packages/Mikado/configuration/configurator.py", line 100, in set_defaults
>     for error in validate_properties(validator, properties, instance, schema):
>   File "/home/user/luohao/anaconda2/envs/mikado/lib/python3.5/site-packages/jsonschema/_validators.py", line 304, in properties_draft4
>     schema_path=property,
>   File "/home/user/luohao/anaconda2/envs/mikado/lib/python3.5/site-packages/jsonschema/validators.py", line 121, in descend
>     for error in self.iter_errors(instance, schema):
>   File "/home/user/luohao/anaconda2/envs/mikado/lib/python3.5/site-packages/jsonschema/validators.py", line 105, in iter_errors
>     for error in errors:
>   File "/home/user/luohao/anaconda2/envs/mikado/lib/python3.5/site-packages/jsonschema/_validators.py", line 341, in oneOf_draft4
>     errs = list(validator.descend(instance, subschema, schema_path=index))
>   File "/home/user/luohao/anaconda2/envs/mikado/lib/python3.5/site-packages/jsonschema/validators.py", line 121, in descend
>     for error in self.iter_errors(instance, schema):
>   File "/home/user/luohao/anaconda2/envs/mikado/lib/python3.5/site-packages/jsonschema/validators.py", line 105, in iter_errors
>     for error in errors:
>   File "/home/user/luohao/anaconda2/envs/mikado/lib/python3.5/site-packages/Mikado/configuration/configurator.py", line 103, in set_defaults
>     instance = set_default(instance, properties, simple_comment=simple)
>   File "/home/user/luohao/anaconda2/envs/mikado/lib/python3.5/site-packages/Mikado/configuration/configurator.py", line 79, in set_default
>     instance[prop] = dict()
> TypeError: 'str' object does not support item assignment
> 2018-10-31 08:04:39,836 - pick_init - pick.py:148 - ERROR - pick - MainProcess - 'str' object does not support item assignment
> 2018-10-31 08:04:39,836 - main - __init__.py:124 - ERROR - main - MainProcess - Mikado crashed, cause:
> 2018-10-31 08:04:39,836 - main - __init__.py:125 - ERROR - main - MainProcess - 'str' object does not support item assignment
> Traceback (most recent call last):
>   File "/home/user/luohao/anaconda2/envs/mikado/lib/python3.5/site-packages/Mikado/__init__.py", line 110, in main
>     args.func(args)
>   File "/home/user/luohao/anaconda2/envs/mikado/lib/python3.5/site-packages/Mikado/subprograms/pick.py", line 149, in pick
>     raise exc
>   File "/home/user/luohao/anaconda2/envs/mikado/lib/python3.5/site-packages/Mikado/subprograms/pick.py", line 146, in pick
>     args = check_run_options(args, logger=logger)
>   File "/home/user/luohao/anaconda2/envs/mikado/lib/python3.5/site-packages/Mikado/subprograms/pick.py", line 121, in check_run_options
>     args.json_conf = check_json(args.json_conf, logger=logger)
>   File "/home/user/luohao/anaconda2/envs/mikado/lib/python3.5/site-packages/Mikado/configuration/configurator.py", line 519, in check_json
>     validator.validate(json_conf)
>   File "/home/user/luohao/anaconda2/envs/mikado/lib/python3.5/site-packages/jsonschema/validators.py", line 129, in validate
>     for error in self.iter_errors(*args, **kwargs):
>   File "/home/user/luohao/anaconda2/envs/mikado/lib/python3.5/site-packages/jsonschema/validators.py", line 105, in iter_errors
>     for error in errors:
>   File "/home/user/luohao/anaconda2/envs/mikado/lib/python3.5/site-packages/Mikado/configuration/configurator.py", line 100, in set_defaults
>     for error in validate_properties(validator, properties, instance, schema):
>   File "/home/user/luohao/anaconda2/envs/mikado/lib/python3.5/site-packages/jsonschema/_validators.py", line 304, in properties_draft4
>     schema_path=property,
>   File "/home/user/luohao/anaconda2/envs/mikado/lib/python3.5/site-packages/jsonschema/validators.py", line 121, in descend
>     for error in self.iter_errors(instance, schema):
>   File "/home/user/luohao/anaconda2/envs/mikado/lib/python3.5/site-packages/jsonschema/validators.py", line 105, in iter_errors
>     for error in errors:
>   File "/home/user/luohao/anaconda2/envs/mikado/lib/python3.5/site-packages/Mikado/configuration/configurator.py", line 100, in set_defaults
>     for error in validate_properties(validator, properties, instance, schema):
>   File "/home/user/luohao/anaconda2/envs/mikado/lib/python3.5/site-packages/jsonschema/_validators.py", line 304, in properties_draft4
>     schema_path=property,
>   File "/home/user/luohao/anaconda2/envs/mikado/lib/python3.5/site-packages/jsonschema/validators.py", line 121, in descend
>     for error in self.iter_errors(instance, schema):
>   File "/home/user/luohao/anaconda2/envs/mikado/lib/python3.5/site-packages/jsonschema/validators.py", line 105, in iter_errors
>     for error in errors:
>   File "/home/user/luohao/anaconda2/envs/mikado/lib/python3.5/site-packages/jsonschema/_validators.py", line 341, in oneOf_draft4
>     errs = list(validator.descend(instance, subschema, schema_path=index))
>   File "/home/user/luohao/anaconda2/envs/mikado/lib/python3.5/site-packages/jsonschema/validators.py", line 121, in descend
>     for error in self.iter_errors(instance, schema):
>   File "/home/user/luohao/anaconda2/envs/mikado/lib/python3.5/site-packages/jsonschema/validators.py", line 105, in iter_errors
>     for error in errors:
>   File "/home/user/luohao/anaconda2/envs/mikado/lib/python3.5/site-packages/Mikado/configuration/configurator.py", line 103, in set_defaults
>     instance = set_default(instance, properties, simple_comment=simple)
>   File "/home/user/luohao/anaconda2/envs/mikado/lib/python3.5/site-packages/Mikado/configuration/configurator.py", line 79, in set_default
>     instance[prop] = dict()
> TypeError: 'str' object does not support item assignment
> 

How could I fix it?

**Comment by lucventurini** [comment]
Dear @lurebgi , 
this seems like an error related to the parsing of the configuration or scoring file(s). Would you please be able to send it over, either here or - if confidentiality is better - at my official email address luca.venturini@earlham.ac.uk?

Kind regards

Luca Venturini

**Comment by lurebgi** [comment]
Adding the patch solved the problem, thank you!
Best regards, Luohao

**Comment by lucventurini** [comment]
Dear Luohao,
                        Excellent to hear! Please let me know of any other problems or bugs you might encounter.

Kind regards

Luca Venturini

Ottieni Outlook per Android<https://aka.ms/ghei36>

________________________________
