### ISSUE TITLE
Docker image error

### ISSUE THREAD

**Issue by mndavies286** [EI-CoreBioinformatics/mikado#164]
Hi

I seem to be having a similar issue to another user. When I run the cyverseuk/mikado mikado configure option in Docker on the sample data, I get the error below. Could you suggest what the issue might be

BW

Matt

2019-03-26 15:47:57,134 - main - __init__.py:124 - ERROR - main - MainProcess - Mikado crashed, cause:
2019-03-26 15:47:57,134 - main - __init__.py:125 - ERROR - main - MainProcess - Malformed inputs file. Error:
could not convert string to float: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/Mikado/subprograms/configure.py", line 217, in create_cohttps://github.com/EI-CoreBioinformatics/mikado/issues/117nfig
    score = float(_fields[3])
ValueError: could not convert string to float: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/Mikado/__init__.py", line 110, in main
    args.func(args)
  File "/usr/local/lib/python3.5/dist-packages/Mikado/subprograms/configure.py", line 222, in create_config
    raise ValueError("Malformed inputs file. Error:\n{}".format(exc))
ValueError: Malformed inputs file. Error:
could not convert string to float:

**Comment by lucventurini** [comment]
Hi @mndavies286 , thank you for reporting, I will have a look.
In the meantime, I can tell you that the Singularity recipes functions properly, if that can be a valid alternative.

**Comment by aliceminotto** [comment]
It may be because I haven't updated cyverseuk/mikado in over 10 months, so it's *some* releases behind this repository. It's not built from the dockerfile in this repo either.

**Comment by mndavies286** [comment]
Hi, thank you for your rapid responses.

I've built a new image from the current Docker file and that seems to have solved the problem. Thanks for your help.

Matt
