### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by rob123king** [EI-CoreBioinformatics/mikado#175]
My gff passes gff validation using gt tools but its failing at mikado compare line somewhere. Any idea how I debug what is wrong with my file for mikado compare?

```
mikado compare -r geneious21.gff -p test2.gff                            2019-05-10 17:48:40,256 - main_queue - compare.py:521 - INFO - compare - MainProcess - Start
2019-05-10 17:48:40,258 - main_queue - compare.py:523 - INFO - compare - MainProcess - Command line: /home/data/bioinf_resources/programming_tools/miniconda3/envs/mikado/bin/mikado compare -r geneious21.gff -p test2.gff
2019-05-10 17:48:40,264 - main_queue - compare.py:567 - INFO - compare - MainProcess - Starting parsing the reference
2019-05-10 17:49:08,888 - main - __init__.py:124 - ERROR - main - MainProcess - Mikado crashed, cause:
2019-05-10 17:49:08,888 - main - __init__.py:125 - ERROR - main - MainProcess - list index out of range
Traceback (most recent call last):
  File "/home/data/bioinf_resources/programming_tools/miniconda3/envs/mikado/lib/python3.6/site-packages/Mikado/__init__.py", line 110, in main
    args.func(args)
  File "/home/data/bioinf_resources/programming_tools/miniconda3/envs/mikado/lib/python3.6/site-packages/Mikado/scales/compare.py", line 573, in compare
    ref_gff=ref_gff)
  File "/home/data/bioinf_resources/programming_tools/miniconda3/envs/mikado/lib/python3.6/site-packages/Mikado/scales/compare.py", line 217, in prepare_reference
    genes, positions = finalize_reference(genes, positions, queue_logger, args)
  File "/home/data/bioinf_resources/programming_tools/miniconda3/envs/mikado/lib/python3.6/site-packages/Mikado/scales/compare.py", line 112, in finalize_reference
    genes[gid].finalize(exclude_utr=args.exclude_utr)
  File "/home/data/bioinf_resources/programming_tools/miniconda3/envs/mikado/lib/python3.6/site-packages/Mikado/loci/reference_gene.py", line 182, in finalize
    self.transcripts[tid].finalize()
  File "/home/data/bioinf_resources/programming_tools/miniconda3/envs/mikado/lib/python3.6/site-packages/Mikado/transcripts/transcript.py", line 979, in finalize
    finalize(self)
  File "/home/data/bioinf_resources/programming_tools/miniconda3/envs/mikado/lib/python3.6/site-packages/Mikado/transcripts/transcript_methods/finalizing.py", line 598, in finalize
    __basic_final_checks(transcript)
  File "/home/data/bioinf_resources/programming_tools/miniconda3/envs/mikado/lib/python3.6/site-packages/Mikado/transcripts/transcript_methods/finalizing.py", line 52, in __basic_final_checks
    if __after[0][0] == transcript.exons[-1][1] + 1:
IndexError: list index out of range

```

**Comment by lucventurini** [comment]
Dear @rob123king ,
                                 thank you for reporting this bug. I suppect that the bug is triggered by some transcripts having partly-mangled UTR or CDS features. GenomeTools does not detect such instances as invalid, whereas Mikado does. E.g. in the mock GFF3 that I attach([test.gff3.txt](https://github.com/EI-CoreBioinformatics/mikado/files/3172188/test.gff3.txt)), transcript1 is clearly invalid (due to having a defined UTR without an accompanying CDS) but GenomeTools formally validates it.

That said, I am currently not being able to replicate the bug you encountered on my end; and it might very well be possible that the triggering transcripts are actually correct. I am therefore modifying the section so that the error will be handled more gracefully and report in the log which transcript(s) trigger the bug, without killing the program.

I hope this will allow us to drill down on the incorrect transcript(s) in your `geneious21.gff` file.

Kind regards

**Comment by lucventurini** [comment]
Dear @rob123king ,
                                
please see the changes in Mikado/transcripts/transcript_methods/finalizing.py implemented in b643c8e3e. To test whether this allows Mikado to report correctly on the issue in the log, you could either install the program from the development branch or patch the relevant file.

I hope this helps.

**Comment by lucventurini** [comment]
Dear @rob123king, any luck with the patched software?

**Comment by lucventurini** [comment]
Closing for now.
