### ISSUE TITLE
Mikado self comparison error - unexpected keyword argument 'fuzzymatch'

### ISSUE THREAD

**Issue by gemygk** [EI-CoreBioinformatics/mikado#176]
Hi Luca,

I am getting an error when I do Mikado '--self' comparison. I am getting the same error even with our previous stable installation - mikado-20190325_c940de1.

Can you please have a look?

```
Mikado version: mikado-20190430_f90a7a4

WD:
/ei/scratch/kaithakg/mikado
Command used:
mikado compare -r chr1A.gtf --self --out mikado-20190430_f90a7a4_self_compare

Error:
Traceback (most recent call last):
  File "/tgac/software/testing/mikado/20190430_f90a7a4/x86_64/lib/python3.6/site-packages/Mikado/__init__.py", line 109, in main
    args.func(args)
  File "/tgac/software/testing/mikado/20190430_f90a7a4/x86_64/lib/python3.6/site-packages/Mikado/scales/compare.py", line 751, in compare
    parse_prediction(args, index_name, queue_logger)
  File "/tgac/software/testing/mikado/20190430_f90a7a4/x86_64/lib/python3.6/site-packages/Mikado/scales/compare.py", line 403, in parse_prediction
    transmitter(done, transcript)
  File "/tgac/software/testing/mikado/20190430_f90a7a4/x86_64/lib/python3.6/site-packages/Mikado/scales/compare.py", line 297, in get_best_result
    assigner_instance.get_best(transcript)
  File "/tgac/software/testing/mikado/20190430_f90a7a4/x86_64/lib/python3.6/site-packages/Mikado/scales/assigner.py", line 726, in get_best
    fuzzymatch=fuzzymatch)
TypeError: self_analyse_prediction() got an unexpected keyword argument 'fuzzymatch'
```

Best,
Gemy

**Comment by lucventurini** [comment]
Hi @gemygk ,
                         many apologies for this, as I changed quite a lot of things under the hood, I kinda left the self-comparison in the dust while I experimented with different parts. I will strive to make Mikado self-compare functional again ASAP.

**Comment by lucventurini** [comment]
Hi @gemygk , I should have fixed Mikado compare self (and internal) now. 
The changes are in the development branch. Soon I hope to merge it back to master.
