### ISSUE TITLE
Mikado compare

### ISSUE THREAD

**Issue by ChemaMD** [EI-CoreBioinformatics/mikado#238]
2019-10-16 13:38:13,815 - main_queue - compare.py:684 - INFO - compare - MainProcess - Start
2019-10-16 13:38:13,817 - main_queue - compare.py:686 - INFO - compare - MainProcess - Command line: /data/home/btx333/.conda/envs/mikado2.1/bin/mikado compare -r mikado.loci.gff3 -p Owenia.Augustus.gtf -o AugustusVSMikado_CDS -l AugustusVSMikado_CDS.log --protein-coding
2019-10-16 13:38:13,819 - main_queue - compare.py:727 - INFO - compare - MainProcess - Index found
2019-10-16 13:38:13,856 - main_queue - compare.py:730 - INFO - compare - MainProcess - Index valid, proceeding.
2019-10-16 13:38:13,918 - main_queue - compare.py:343 - INFO - parse_prediction - MainProcess - Starting to parse the prediction
2019-10-16 13:38:31,928 - stat_logger - accountant.py:52 - INFO - __init__ - MainProcess - Starting loading the reference for the accountant None
2019-10-16 13:38:33,174 - main_queue - compare.py:756 - ERROR - compare - MainProcess - list index out of range
Traceback (most recent call last):
  File "/data/home/btx333/.conda/envs/mikado2.1/lib/python3.7/site-packages/Mikado/scales/compare.py", line 754, in compare
    parse_prediction(args, index_name, queue_logger)
  File "/data/home/btx333/.conda/envs/mikado2.1/lib/python3.7/site-packages/Mikado/scales/compare.py", line 417, in parse_prediction
    transmitter(done, transcript)
  File "/data/home/btx333/.conda/envs/mikado2.1/lib/python3.7/site-packages/Mikado/scales/compare.py", line 308, in get_best_result
    assigner_instance.get_best(transcript)
  File "/data/home/btx333/.conda/envs/mikado2.1/lib/python3.7/site-packages/Mikado/scales/assigner.py", line 749, in get_best
    results, best_result = self.__prepare_result(prediction, distances, fuzzymatch=fuzzymatch)
  File "/data/home/btx333/.conda/envs/mikado2.1/lib/python3.7/site-packages/Mikado/scales/assigner.py", line 529, in __prepare_result
    results, best_result = self.__check_for_fusions(prediction, matches, fuzzymatch=fuzzymatch)
  File "/data/home/btx333/.conda/envs/mikado2.1/lib/python3.7/site-packages/Mikado/scales/assigner.py", line 438, in __check_for_fusions
    if new_matches[gene][0].j_f1[0] == 0 and new_matches[gene][0].n_recall[0] < 10:
IndexError: list index out of range

**Comment by lucventurini** [comment]
Hi @ChemaMD, I have found and corrected the bug. I will add a test to prevent regression then merge back into the `master` trunk.
