### ISSUE TITLE
Error off parser and missing chromosomes

### ISSUE THREAD

**Issue by fmarletaz** [EI-CoreBioinformatics/mikado#262]
Hi -
I tried to run mikado (2rc4) to annotate a genome with 3 datasets (isoseq and trinity aligned with gmap plus string tie). The run finished but when I checked the files afterward, I realized some entire chromosomes, segments of chromosomes were completely empty in the output (mikado.loci.gff3). My hypothesis is that it is related to very long introns, especially in the isoseq datasets, so I wanted to try 2rc6 to limit the maximum intron size. I am currently trying without the iseseq data. 
However, when I try to install and run 2rc6, I have an error at the `prepare` stage with the gff parser (see below). Thanks
```
2020-01-31 17:46:04,853 - prepare - prepare.py:91 - INFO - setup - MainProcess - Command line: /home/f/fmarletaz/work/miniconda2/envs/Mikado/bin/mikado prepare --json-conf configuration.yaml
2020-01-31 17:46:04,853 - prepare - prepare.py:92 - INFO - setup - MainProcess - Random seed: 3562101224
2020-01-31 17:46:05,667 - prepare - prepare.py:477 - INFO - prepare - MainProcess - Output dir: .. Output GTF: ./mikado_prepared.gtf. Output Fasta: ./mikado_prepared.fasta
2020-01-31 17:46:05,667 - prepare - prepare.py:478 - INFO - prepare - MainProcess - Loading reference file
2020-01-31 17:46:05,692 - prepare - prepare.py:480 - INFO - prepare - MainProcess - Finished loading genome file
2020-01-31 17:46:05,692 - prepare - prepare.py:481 - INFO - prepare - MainProcess - Started loading exon lines
2020-01-31 17:46:05,692 - prepare - prepare.py:311 - INFO - _load_exon_lines_multi - MainProcess - Starting to load lines from 3 files (using 3 processes)
2020-01-31 17:46:08,083 - prepare.AnnotationParser-2 - annotation_parser.py:137 - ERROR - run - AnnotationParser-2 - <built-in function fast_int> returned NULL without setting an error
Traceback (most recent call last):
  File "/home/f/fmarletaz/work/miniconda2/envs/Mikado/lib/python3.7/site-packages/Mikado/preparation/annotation_parser.py", line 101, in run
    strand_specific=strand_specific)
  File "/home/f/fmarletaz/work/miniconda2/envs/Mikado/lib/python3.7/site-packages/Mikado/preparation/annotation_parser.py", line 429, in load_from_gff
    for row in gff_handle:
  File "/home/f/fmarletaz/work/miniconda2/envs/Mikado/lib/python3.7/site-packages/Mikado/parsers/GFF.py", line 367, in __next__
    line = GffLine(line)
  File "/home/f/fmarletaz/work/miniconda2/envs/Mikado/lib/python3.7/site-packages/Mikado/parsers/GFF.py", line 36, in __init__
    GFAnnotation.__init__(self, line, my_line, header=header)
  File "/home/f/fmarletaz/work/miniconda2/envs/Mikado/lib/python3.7/site-packages/Mikado/parsers/gfannotation.py", line 92, in __init__
    self.start, self.end = tuple(fastnumbers.fast_int(i) for i in self._fields[3:5])
  File "/home/f/fmarletaz/work/miniconda2/envs/Mikado/lib/python3.7/site-packages/Mikado/parsers/gfannotation.py", line 92, in <genexpr>
    self.start, self.end = tuple(fastnumbers.fast_int(i) for i in self._fields[3:5])
SystemError: <built-in function fast_int> returned NULL without setting an error
2020-01-31 17:46:13,722 - prepare.AnnotationParser-3 - annotation_parser.py:137 - ERROR - run - AnnotationParser-3 - <built-in function fast_int> returned NULL without setting an error
Traceback (most recent call last):
  File "/home/f/fmarletaz/work/miniconda2/envs/Mikado/lib/python3.7/site-packages/Mikado/preparation/annotation_parser.py", line 112, in run
    strand_specific=strand_specific)
  File "/home/f/fmarletaz/work/miniconda2/envs/Mikado/lib/python3.7/site-packages/Mikado/preparation/annotation_parser.py", line 583, in load_from_gtf
    for row in gff_handle:
  File "/home/f/fmarletaz/work/miniconda2/envs/Mikado/lib/python3.7/site-packages/Mikado/parsers/GTF.py", line 401, in __next__
    return GtfLine(line)
  File "/home/f/fmarletaz/work/miniconda2/envs/Mikado/lib/python3.7/site-packages/Mikado/parsers/GTF.py", line 46, in __init__
    super().__init__(line, my_line, header=header)
  File "/home/f/fmarletaz/work/miniconda2/envs/Mikado/lib/python3.7/site-packages/Mikado/parsers/gfannotation.py", line 92, in __init__
    self.start, self.end = tuple(fastnumbers.fast_int(i) for i in self._fields[3:5])
  File "/home/f/fmarletaz/work/miniconda2/envs/Mikado/lib/python3.7/site-packages/Mikado/parsers/gfannotation.py", line 92, in <genexpr>
    self.start, self.end = tuple(fastnumbers.fast_int(i) for i in self._fields[3:5])
SystemError: <built-in function fast_int> returned NULL without setting an error

```

**Comment by lucventurini** [comment]
Hi @fmarletaz ,
                          thank you for reporting. Something is off - I cannot get `fastnumbers.fast_int` to throw a `SystemError` like it does on your system.

I would need the following to further diagnose the problem:
- could you please confirm whether you are using the tagged release or the latest commit to `master` (887a723). I do not think that commits after the tagging would influence the result, but it would be good to know. 
- I have modified the offending python module in 0571586 (which derives from the most recent `master` branch commit). If you could rerun from the version pulled from the branch (or alternatively, amend the file yourself as shown in the commit), then rerun, we should be able to pinpoint the offending line. This should allow us to put a proper patch on.

Best

**Comment by fmarletaz** [comment]
I just cloned like `git clone...` so I guess the latest commit. 
Here is the output with your modification,  but I am not sure I see the difference. 

```
Process AnnotationParser-2:
Traceback (most recent call last):
  File "/home/f/fmarletaz/work/miniconda2/envs/Mikado/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/f/fmarletaz/work/miniconda2/envs/Mikado/lib/python3.7/site-packages/Mikado/preparation/annotation_parser.py", line 101, in run
    strand_specific=strand_specific)
  File "/home/f/fmarletaz/work/miniconda2/envs/Mikado/lib/python3.7/site-packages/Mikado/preparation/annotation_parser.py", line 429, in load_from_gff
    for row in gff_handle:
  File "/home/f/fmarletaz/work/miniconda2/envs/Mikado/lib/python3.7/site-packages/Mikado/parsers/GFF.py", line 367, in __next__
    line = GffLine(line)
  File "/home/f/fmarletaz/work/miniconda2/envs/Mikado/lib/python3.7/site-packages/Mikado/parsers/GFF.py", line 36, in __init__
    GFAnnotation.__init__(self, line, my_line, header=header)
  File "/home/f/fmarletaz/work/miniconda2/envs/Mikado/lib/python3.7/site-packages/Mikado/parsers/gfannotation.py", line 92, in __init__
    self.start, self.end = tuple(fastnumbers.fast_int(i) for i in self._fields[3:5])
  File "/home/f/fmarletaz/work/miniconda2/envs/Mikado/lib/python3.7/site-packages/Mikado/parsers/gfannotation.py", line 92, in <genexpr>
    self.start, self.end = tuple(fastnumbers.fast_int(i) for i in self._fields[3:5])
SystemError: <built-in function fast_int> returned NULL without setting an error

Process AnnotationParser-1:
Traceback (most recent call last):
  File "/home/f/fmarletaz/work/miniconda2/envs/Mikado/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/f/fmarletaz/work/miniconda2/envs/Mikado/lib/python3.7/site-packages/Mikado/preparation/annotation_parser.py", line 101, in run
    strand_specific=strand_specific)
  File "/home/f/fmarletaz/work/miniconda2/envs/Mikado/lib/python3.7/site-packages/Mikado/preparation/annotation_parser.py", line 429, in load_from_gff
    for row in gff_handle:
  File "/home/f/fmarletaz/work/miniconda2/envs/Mikado/lib/python3.7/site-packages/Mikado/parsers/GFF.py", line 367, in __next__
    line = GffLine(line)
  File "/home/f/fmarletaz/work/miniconda2/envs/Mikado/lib/python3.7/site-packages/Mikado/parsers/GFF.py", line 36, in __init__
    GFAnnotation.__init__(self, line, my_line, header=header)
  File "/home/f/fmarletaz/work/miniconda2/envs/Mikado/lib/python3.7/site-packages/Mikado/parsers/gfannotation.py", line 92, in __init__
    self.start, self.end = tuple(fastnumbers.fast_int(i) for i in self._fields[3:5])
  File "/home/f/fmarletaz/work/miniconda2/envs/Mikado/lib/python3.7/site-packages/Mikado/parsers/gfannotation.py", line 92, in <genexpr>
    self.start, self.end = tuple(fastnumbers.fast_int(i) for i in self._fields[3:5])
SystemError: <built-in function fast_int> returned NULL without setting an error
Process AnnotationParser-3:
Traceback (most recent call last):
  File "/home/f/fmarletaz/work/miniconda2/envs/Mikado/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/f/fmarletaz/work/miniconda2/envs/Mikado/lib/python3.7/site-packages/Mikado/preparation/annotation_parser.py", line 112, in run
    strand_specific=strand_specific)
  File "/home/f/fmarletaz/work/miniconda2/envs/Mikado/lib/python3.7/site-packages/Mikado/preparation/annotation_parser.py", line 583, in load_from_gtf
    for row in gff_handle:
  File "/home/f/fmarletaz/work/miniconda2/envs/Mikado/lib/python3.7/site-packages/Mikado/parsers/GTF.py", line 401, in __next__
    return GtfLine(line)
  File "/home/f/fmarletaz/work/miniconda2/envs/Mikado/lib/python3.7/site-packages/Mikado/parsers/GTF.py", line 46, in __init__
    super().__init__(line, my_line, header=header)
  File "/home/f/fmarletaz/work/miniconda2/envs/Mikado/lib/python3.7/site-packages/Mikado/parsers/gfannotation.py", line 92, in __init__
    self.start, self.end = tuple(fastnumbers.fast_int(i) for i in self._fields[3:5])
  File "/home/f/fmarletaz/work/miniconda2/envs/Mikado/lib/python3.7/site-packages/Mikado/parsers/gfannotation.py", line 92, in <genexpr>
    self.start, self.end = tuple(fastnumbers.fast_int(i) for i in self._fields[3:5])
SystemError: <built-in function fast_int> returned NULL without setting an error
Mikado prepare has finished correctly. The output ./mikado_prepared.fasta FASTA file can now be used for BLASTX and/or ORF calling before the next step in the pipeline, `mikado serialise`.
```

**Comment by cschu** [comment]
> I just cloned like `git clone...` so I guess the latest commit.
> Here is the output with your modification, but I am not sure I see the difference.

Hi @fmarletaz,

Could you do a `git log -n 1` in the mikado directory and paste the output here (or just the commit hash (first line)), please? With git clone It should be the latest commit at the time, but better to know for certain.

Thanks,
Christian

**Comment by lucventurini** [comment]
Hi @fmarletaz ,
to complete what @cschu said, the commit I made is in a different branch from `master`. Apologies for not having been clear on that. The following should work:

```
git clone ...
cd mikado
git checkout issue-262
git log -n 1   # To verify it is the correct commit
```
Best

**Comment by fmarletaz** [comment]
Ok, thanks, I guess I managed to use the properly patched version. Here is the output file:
[prepare.log](https://github.com/EI-CoreBioinformatics/mikado/files/4151607/prepare.log)

**Comment by lucventurini** [comment]
Hi @fmarletaz, reading the log, the GTF line that triggered the error seems fine, which is puzzling. 

However, there is another error further down which seems to indicate a problem with the Sqlite3 temporary databases used by `mikado prepare` to cache the results of the parsing. My question then is, are you working on a shared filesystem connected through NFS? This creates problems for SQLITE3.

**Comment by fmarletaz** [comment]
Hi @lucventurini 
To mention, I tried to rerun with version 2rc4 and it did not throw any error. It is a shared filesystem indeed but I don't know if it runs with NFS, I can investigate. Was the previous versions also using Sqlite3?

**Comment by lucventurini** [comment]
Hi @fmarletaz, yes, also the previous version was using Sqlite3.

However, the details of how `mikado prepare` connects to these temporary caches are different. This is possibly the origin of the bug. To test this, I have just created a patched version in a branch. To test, would you please be able to do the following:

```cd mikado/
git remote add lucventurini https://github.com/lucventurini/mikado.git
git pull lucventurini master
git checkout lucventurini-path-i262  # Switch to branch with the patch
git pull
## Install
```

Thank you!

**Comment by lucventurini** [comment]
Hi @fmarletaz , I have decided to cut the head of the bull, as we say in Italy, and I changed the offending line in 9058233 (directly in `master`).

I will close the issue for now as the bug should now be solved.
