### ISSUE TITLE
Mikado pick

### ISSUE THREAD

**Issue by francicco** [EI-CoreBioinformatics/mikado#316]
Hi,

I'm getting these type of errors while running `mikado pick`:

```
Process LociProcesser-3:
Traceback (most recent call last):
  File "/mnt/storage/home/tk19812/.local/lib/python3.7/site-packages/Mikado/parsers/gfannotation.py", line 93, in __init__
    self.start, self.end = tuple(fast_int(i, default=None) for i in self._fields[3:5])
  File "/mnt/storage/home/tk19812/.local/lib/python3.7/site-packages/Mikado/parsers/gfannotation.py", line 93, in <genexpr>
    self.start, self.end = tuple(fast_int(i, default=None) for i in self._fields[3:5])
SystemError: <built-in function fast_int> returned NULL without setting an error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/software/languages/anaconda/Anaconda3-2020.02-tflow-1.15/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/mnt/storage/home/tk19812/.local/lib/python3.7/site-packages/Mikado/picking/loci_processer.py", line 506, in run
    definition = GtfLine(tjson["definition"]).as_dict()
  File "/mnt/storage/home/tk19812/.local/lib/python3.7/site-packages/Mikado/parsers/GTF.py", line 46, in __init__
    super().__init__(line, my_line, header=header)
  File "/mnt/storage/home/tk19812/.local/lib/python3.7/site-packages/Mikado/parsers/gfannotation.py", line 95, in __init__
    raise ValueError("Invalid start and end values: {}".format(" ".join(self._fields[3:5])))
ValueError: Invalid start and end values: 9641275 9656989
Process LociProcesser-4:
Traceback (most recent call last):
  File "/mnt/storage/software/languages/anaconda/Anaconda3-2020.02-tflow-1.15/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/mnt/storage/home/tk19812/.local/lib/python3.7/site-packages/Mikado/picking/loci_processer.py", line 550, in run
    print_subloci=print_subloci)
  File "/mnt/storage/home/tk19812/.local/lib/python3.7/site-packages/Mikado/picking/_loci_serialiser.py", line 33, in serialise_locus
    sub_metrics_rows = [_ for _ in stranded_locus.print_subloci_metrics() if _ != {} and "tid" in _]
  File "/mnt/storage/home/tk19812/.local/lib/python3.7/site-packages/Mikado/picking/_loci_serialiser.py", line 33, in <listcomp>
    sub_metrics_rows = [_ for _ in stranded_locus.print_subloci_metrics() if _ != {} and "tid" in _]
  File "/mnt/storage/home/tk19812/.local/lib/python3.7/site-packages/Mikado/loci/superlocus.py", line 1086, in print_subloci_metrics
    for row in slocus.print_metrics():
  File "/mnt/storage/home/tk19812/.local/lib/python3.7/site-packages/Mikado/loci/sublocus.py", line 307, in print_metrics
    self.metric_lines_store = [_ for _ in self.prepare_metrics()]
  File "/mnt/storage/home/tk19812/.local/lib/python3.7/site-packages/Mikado/loci/sublocus.py", line 307, in <listcomp>
    self.metric_lines_store = [_ for _ in self.prepare_metrics()]
  File "/mnt/storage/home/tk19812/.local/lib/python3.7/site-packages/Mikado/loci/sublocus.py", line 292, in prepare_metrics
    for row in Abstractlocus.print_metrics(self):
  File "/mnt/storage/home/tk19812/.local/lib/python3.7/site-packages/Mikado/loci/abstractlocus.py", line 1024, in print_metrics
    if isfloat(value):
SystemError: <built-in function isfloat> returned NULL without setting an error
Process LociProcesser-1:
Traceback (most recent call last):
  File "/mnt/storage/software/languages/anaconda/Anaconda3-2020.02-tflow-1.15/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/mnt/storage/home/tk19812/.local/lib/python3.7/site-packages/Mikado/picking/loci_processer.py", line 550, in run
    print_subloci=print_subloci)
  File "/mnt/storage/home/tk19812/.local/lib/python3.7/site-packages/Mikado/picking/_loci_serialiser.py", line 33, in serialise_locus
    sub_metrics_rows = [_ for _ in stranded_locus.print_subloci_metrics() if _ != {} and "tid" in _]
  File "/mnt/storage/home/tk19812/.local/lib/python3.7/site-packages/Mikado/picking/_loci_serialiser.py", line 33, in <listcomp>
    sub_metrics_rows = [_ for _ in stranded_locus.print_subloci_metrics() if _ != {} and "tid" in _]
  File "/mnt/storage/home/tk19812/.local/lib/python3.7/site-packages/Mikado/loci/superlocus.py", line 1086, in print_subloci_metrics
    for row in slocus.print_metrics():
  File "/mnt/storage/home/tk19812/.local/lib/python3.7/site-packages/Mikado/loci/sublocus.py", line 307, in print_metrics
    self.metric_lines_store = [_ for _ in self.prepare_metrics()]
  File "/mnt/storage/home/tk19812/.local/lib/python3.7/site-packages/Mikado/loci/sublocus.py", line 307, in <listcomp>
    self.metric_lines_store = [_ for _ in self.prepare_metrics()]
  File "/mnt/storage/home/tk19812/.local/lib/python3.7/site-packages/Mikado/loci/sublocus.py", line 292, in prepare_metrics
    for row in Abstractlocus.print_metrics(self):
  File "/mnt/storage/home/tk19812/.local/lib/python3.7/site-packages/Mikado/loci/abstractlocus.py", line 1024, in print_metrics
    if isfloat(value):
SystemError: <built-in function isfloat> returned NULL without setting an error
^[[B^[[B^CTraceback (most recent call last):
  File "/mnt/storage/home/tk19812/.local/lib/python3.7/site-packages/Mikado/__init__.py", line 106, in main
    args.func(args)
  File "/mnt/storage/home/tk19812/.local/lib/python3.7/site-packages/Mikado/subprograms/pick.py", line 225, in pick
    creator()
  File "/mnt/storage/home/tk19812/.local/lib/python3.7/site-packages/Mikado/picking/picker.py", line 1154, in __call__
    self._parse_and_submit_input()
  File "/mnt/storage/home/tk19812/.local/lib/python3.7/site-packages/Mikado/picking/picker.py", line 1120, in _parse_and_submit_input
    self.__submit_multi_threading()
  File "/mnt/storage/home/tk19812/.local/lib/python3.7/site-packages/Mikado/picking/picker.py", line 768, in __submit_multi_threading
    counter, chrom, num_genes, loci, subloci, monoloci = status_queue.get()
  File "/mnt/storage/software/languages/anaconda/Anaconda3-2020.02-tflow-1.15/lib/python3.7/multiprocessing/queues.py", line 94, in get
    res = self._recv_bytes()
  File "/mnt/storage/software/languages/anaconda/Anaconda3-2020.02-tflow-1.15/lib/python3.7/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/mnt/storage/software/languages/anaconda/Anaconda3-2020.02-tflow-1.15/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/mnt/storage/software/languages/anaconda/Anaconda3-2020.02-tflow-1.15/lib/python3.7/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
KeyboardInterrupt
```

How do I fix that?
Thanks 
Francesco

**Comment by lucventurini** [comment]
Dear @francicco 

This error is analogous to the error present in #317 and is caused by the same library (`fastnumbers`).
I would be loathe to remove it from Mikado because it really does improve parsing times, but we need to make sure that it is not crashing the program.

If you could follow the instructions in #317 we can get to the bottom of this.

Many thanks

**Comment by lucventurini** [comment]
Dear @francicco 

I have now proceeded to completely remove `fastnumbers` from the Mikado codebase. This should solve for good your problem.

I hope this helps!

**Comment by francicco** [comment]
Hi Luca,

Thanks a lot!!!! It works now. I have a lot of warnings now, some transcripts are discarded. I guess I have to check it conversion from bed12 to gff3 works fine. Any advice?
Cheers
F

**Comment by lucventurini** [comment]
Hi @francicco 

Oh great to hear! It's good to have removed one issue.

Regarding the conversion from BED12 to GFF3 ... it can be tricky.
First off, though, it might not be necessary: `mikado prepare` **is** capable of accepting BED12 and BAM inputs.

For the conversion, we do have an in-house solution:

```python
mikado util convert -if bed12 -of gff3 INPUT_FILE OUTPUT_FILE
```

The caveat is that each transcript line will be converted (and put into a gene) of its own.

Another strong possibility, which is much faster than Mikado as it's written in C, it's `gffread`:

```bash
gffread --in-bed INPUT_FILE > OUTPUT_FILE
```

You could also use `genometools`, eg

```bash
gt bed_to_gff3 INPUT_FILE > OUTPUT_FILE
```

However, for `genometools`, you should make sure that the 4th field for the name only contains a single string (no "ID=" etc.). Also the output will have to be massaged before inputing into Mikado ("BED_feature" to "transcript", remove "BED_thick_feature", "BED_block" to "exon").

May I ask how you did convert the files initially?

**Comment by francicco** [comment]
Hi Luca,

I'm making my own script, but if mikado takes BED12, I'll also try with it.
I can try using also one of your suggestions to check my own.

Cheers
F
