### ISSUE TITLE
Tuple index out of range error in mikado compare

### ISSUE THREAD

**Issue by ddpinto** [EI-CoreBioinformatics/mikado#318]
Dear Mikado team,
When running with a large gtf input file with >500,000 transcript entries, I encountered the following error during the writing of the 'refmap' file when running "mikado compare --self":

```2020-07-06 11:29:57,827 - main_queue - compare.py:904 - ERROR - compare - MainProcess - tuple index out of range
Traceback (most recent call last):
  File "/hpc/users/pintod02/.conda/envs/mikado/lib/python3.7/site-packages/Mikado/scales/compare.py", line 902, in compare
    parse_prediction(args, index_name, queue_logger)
  File "/hpc/users/pintod02/.conda/envs/mikado/lib/python3.7/site-packages/Mikado/scales/compare.py", line 666, in parse_prediction
    assigner_instance.finish()
  File "/hpc/users/pintod02/.conda/envs/mikado/lib/python3.7/site-packages/Mikado/scales/assigner.py", line 799, in finish
    self.print_refmap()
  File "/hpc/users/pintod02/.conda/envs/mikado/lib/python3.7/site-packages/Mikado/scales/assigner.py", line 1020, in print_refmap
    row[8]  # Location
IndexError: tuple index out of range
2020-07-06 11:29:57,858 - main - __init__.py:120 - ERROR - main - MainProcess - Mikado crashed, cause:
2020-07-06 11:29:57,859 - main - __init__.py:121 - ERROR - main - MainProcess - tuple index out of range
Traceback (most recent call last):
  File "/hpc/users/pintod02/.conda/envs/mikado/lib/python3.7/site-packages/Mikado/__init__.py", line 106, in main
    args.func(args)
  File "/hpc/users/pintod02/.conda/envs/mikado/lib/python3.7/site-packages/Mikado/scales/compare.py", line 902, in compare
    parse_prediction(args, index_name, queue_logger)
  File "/hpc/users/pintod02/.conda/envs/mikado/lib/python3.7/site-packages/Mikado/scales/compare.py", line 666, in parse_prediction
    assigner_instance.finish()
  File "/hpc/users/pintod02/.conda/envs/mikado/lib/python3.7/site-packages/Mikado/scales/assigner.py", line 799, in finish
    self.print_refmap()
  File "/hpc/users/pintod02/.conda/envs/mikado/lib/python3.7/site-packages/Mikado/scales/assigner.py", line 1020, in print_refmap
    row[8]  # Location
IndexError: tuple index out of range```

**Comment by lucventurini** [comment]
Dear @ddpinto 

Apologies for the late reply but I had been busy with another project and subsequently, on holiday. 
Thank you for reporting this bug. Unfortunately as it is, the bug report does not enable us to diagnose the problem correctly.

Could you please provide us the version of the code you used, and tell us how you installed it?
If you were also able to please share with us, **with the understanding of absolute confidentiality on our side**, the file that causes the bug, we could speed up the bug solving.

Many thanks

**Comment by ddpinto** [comment]
Dear @lucventurini 
Thanks for getting back to me. Please see attached for an example test case that gives the error.
[chr14-test-input.tar.gz](https://github.com/EI-CoreBioinformatics/mikado/files/5048549/chr14-test-input.tar.gz)

Many thanks

**Comment by lucventurini** [comment]
@ddpinto 

Many thanks for the test inputs! I can reproduce the bug on my end. I will be working on it today, hopefully I have a fix soon.

Kind regards

**Comment by lucventurini** [comment]
Dear @ddpinto 

I found the cause of the bug - your GTF file contains both transcripts that have a "gene" top-level feature, as well as PacBio transcripts that are not associated to any of it.

I am not sure why this quirk triggers the bug yet, but I should be able to get it controlled soon enough.

Kind regards

**Comment by ddpinto** [comment]
Many thanks for looking into this @lucventurini. Would it help if I remove the gene entries or should I wait for the fix?

**Comment by ddpinto** [comment]
@lucventurini I tried removing the gene entries, but I get the same error.
