### ISSUE TITLE
Mikado crashed when creating the configuration file from the tutorial 

### ISSUE THREAD

**Issue by gc-github-bio** [EI-CoreBioinformatics/mikado#333]
Hi Luca,
I am trying to run a test run following the tutorial, but 'mikado configure' is crashing.
Am I doing something wrong?
Thanks,
Gianni

mikado configure --list list.txt --reference chr5.fas --mode permissive --scoring plant.yaml  --copy-scoring plant.yaml --junctions junctions.bed -bt uniprot_sprot_plants.fasta configuration.yaml
2020-10-28 16:43:24,939 - main - __init__.py:109 - ERROR - main - MainProcess - Mikado crashed, cause:
2020-10-28 16:43:24,939 - main - __init__.py:110 - ERROR - main - MainProcess - 
Traceback (most recent call last):
  File "/home/gc/anaconda3/envs/mikado2/lib/python3.8/site-packages/Mikado/__init__.py", line 95, in main
    args.func(args)
  File "/home/gc/anaconda3/envs/mikado2/lib/python3.8/site-packages/Mikado/subprograms/configure.py", line 279, in create_config
    assert "codon_table" in config["serialise"]
AssertionError

**Comment by lucventurini** [comment]
Dear Gianni,

Many thanks for reporting the bug!
fa6f1b1 successfully closes it.

Kind regards
