### ISSUE TITLE
mikado prepare crash

### ISSUE THREAD

**Issue by gc-github-bio** [EI-CoreBioinformatics/mikado#334]
Hi Luca,

mikado configure went through with the fix you added.
But in the next step of the tutorial, mikado prepare is giving an 'AttributeError'.

Gianni

mikado prepare --json-conf configuration.yaml
2020-10-29 15:34:22,503 - main - __init__.py:109 - ERROR - main - MainProcess - Mikado crashed, cause:
2020-10-29 15:34:22,503 - main - __init__.py:110 - ERROR - main - MainProcess - 
Traceback (most recent call last):
  File "/home/gc/anaconda3/envs/mikado2/lib/python3.8/site-packages/Mikado/__init__.py", line 95, in main
    args.func(args)
  File "/home/gc/anaconda3/envs/mikado2/lib/python3.8/site-packages/Mikado/subprograms/prepare.py", line 233, in prepare_launcher
    prepare(args, logger)
  File "/home/gc/anaconda3/envs/mikado2/lib/python3.8/site-packages/Mikado/preparation/prepare.py", line 545, in prepare
    raise AttributeError
AttributeError

**Comment by lucventurini** [comment]
Dear @gc-github-bio 

Unfortunately this time I am not able to reproduce the bug. 

The error code should have been clearer, I will amend it now, but the reason `prepare` crashes is due to the program not finding the genome FASTA file.

Does the file `chr5.fas` exist? It is compressed in the `sample_data` folder, by default. If only `chr5.fas.gz` is present.

**Comment by gc-github-bio** [comment]
Oh you are right, I had to extract the .fas file in the folder used by conda env. I was using the wrong sample_data folder.
Thank you,
Gianni
