### ISSUE TITLE
Mikado prepare only gathering one gff/gtf file

### ISSUE THREAD

**Issue by 14zac2** [EI-CoreBioinformatics/mikado#339]
Hello!

I'm having some trouble with Mikado only gathering one of my gff/gtf files in mikado_prepared.gtf during mikado prepare. I am using Mikado v2.0rc5 and my gtf files were all prepared with gffread -T to ensure consistency between my files. Only one of these files (there are three) had a Name attribute, so I got rid of this in case it was throwing the error. In mikado_prepared.gtf, only one of my files was present with a very reduced number of transcripts. I tried changing up the order of list.txt just in case this changed anything, and it didn't. The same file was still kept. I am seeing the errors in my prepare.log file. The portion with the error is as follows:

2020-11-25 18:43:33,046 - prepare - prepare.py:395 - INFO - load_exon_lines - MainProcess - Finished loading lines from 3 files
2020-11-25 18:43:33,046 - prepare - prepare.py:489 - INFO - prepare - MainProcess - Finished loading exon lines
2020-11-25 18:43:33,284 - Checker-2 - checking.py:130 - ERROR - create_transcript - Checker-2 - 'str' object has no attribute 'lett
ers'
Traceback (most recent call last):
  File "/home/zclarke/bin/mikado_env/lib/python3.6/site-packages/Mikado/preparation/checking.py", line 113, in create_transcript
    transcript_object.check_orf()
  File "/home/zclarke/bin/mikado_env/lib/python3.6/site-packages/Mikado/transcripts/transcriptchecker.py", line 339, in check_orf
    orfs = list(self.get_internal_orf_beds())
  File "/home/zclarke/bin/mikado_env/lib/python3.6/site-packages/Mikado/transcripts/transcript.py", line 959, in get_internal_orf_b
eds
    table=self.codon_table)
  File "/home/zclarke/bin/mikado_env/lib/python3.6/site-packages/Mikado/parsers/bed12.py", line 354, in __init__
    self.__check_validity(transcriptomic, fasta_index, sequence)
  File "/home/zclarke/bin/mikado_env/lib/python3.6/site-packages/Mikado/parsers/bed12.py", line 599, in __check_validity
    gap='N')
  File "/home/zclarke/bin/mikado_env/lib/python3.6/site-packages/Mikado/parsers/bed12.py", line 138, in _translate_str
    forward_table, valid_letters = get_tables(table, to_stop=to_stop)
  File "/home/zclarke/bin/mikado_env/lib/python3.6/site-packages/Mikado/parsers/bed12.py", line 59, in get_tables
    if table.nucleotide_alphabet.letters is not None:
AttributeError: 'str' object has no attribute 'letters'
2020-11-25 18:43:33,284 - Checker-3 - checking.py:130 - ERROR - create_transcript - Checker-3 - 'str' object has no attribute 'letters'
Traceback (most recent call last):
  File "/home/zclarke/bin/mikado_env/lib/python3.6/site-packages/Mikado/preparation/checking.py", line 113, in create_transcript
    transcript_object.check_orf()
  File "/home/zclarke/bin/mikado_env/lib/python3.6/site-packages/Mikado/transcripts/transcriptchecker.py", line 339, in check_orf
    orfs = list(self.get_internal_orf_beds())
  File "/home/zclarke/bin/mikado_env/lib/python3.6/site-packages/Mikado/transcripts/transcript.py", line 959, in get_internal_orf_beds
    table=self.codon_table)
  File "/home/zclarke/bin/mikado_env/lib/python3.6/site-packages/Mikado/parsers/bed12.py", line 354, in __init__
    self.__check_validity(transcriptomic, fasta_index, sequence)
  File "/home/zclarke/bin/mikado_env/lib/python3.6/site-packages/Mikado/parsers/bed12.py", line 599, in __check_validity
    gap='N')
  File "/home/zclarke/bin/mikado_env/lib/python3.6/site-packages/Mikado/parsers/bed12.py", line 138, in _translate_str
    forward_table, valid_letters = get_tables(table, to_stop=to_stop)
  File "/home/zclarke/bin/mikado_env/lib/python3.6/site-packages/Mikado/parsers/bed12.py", line 59, in get_tables
    if table.nucleotide_alphabet.letters is not None:
AttributeError: 'str' object has no attribute 'letters'
2020-11-25 18:43:33,284 - Checker-4 - checking.py:130 - ERROR - create_transcript - Checker-4 - 'str' object has no attribute 'letters'

The error continues as such. Do you have any idea what might be going on here?

Thanks so much for your help and your time,
Zoe

**Comment by 14zac2** [comment]
Hi - just wanted to follow up by saying I have tried this with your distribution of Mikado for python 3.7 (same release version) and the issue is resolved. I'm assuming, then, that this issue is more related to python 3.6 than the input files.

Thanks,
Zoe

**Comment by lucventurini** [comment]
Hi @14zac2 

Sorry for the late reply. I think the issue is related to the version of BioPython being too old - they changed a lot in the Alphabet module, in the past year, and I had to accommodate the code in a non-retrocompatible way to make Mikado function with the new version.

Glad that you could solve it nonetheless.
