### ISSUE TITLE
Pick error assert transcript.retained_intron_num > 0

### ISSUE THREAD

**Issue by swarbred** [EI-CoreBioinformatics/mikado#351]
Seeing this in the pick logs for runs using mikado-issue-340-reference-update

e.g. /ei/workarea/group-ga/Projects/CB-GENANNO-477_Minos_Arabidopsis/Analysis/mikado-issue-340-reference-update/PickRun2_reference-update_check_refs/pick.log

2020-12-09 20:19:08,324 - Chr1:4954032-4959529 - loci_processer.py:286 - ERROR - analyse_locus - LociProcesser-20 - 
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/Mikado/picking/loci_processer.py", line 280, in analyse_locus
    stranded_locus.define_loci()
  File "/usr/local/lib/python3.7/site-packages/Mikado/loci/superlocus.py", line 1219, in define_loci
    self.define_alternative_splicing()
  File "/usr/local/lib/python3.7/site-packages/Mikado/loci/superlocus.py", line 1359, in define_alternative_splicing
    self.loci[lid].finalize_alternative_splicing()
  File "/usr/local/lib/python3.7/site-packages/Mikado/loci/locus.py", line 227, in finalize_alternative_splicing
    with_retained = self._remove_retained_introns()
  File "/usr/local/lib/python3.7/site-packages/Mikado/loci/locus.py", line 372, in _remove_retained_introns
    assert transcript.retained_intron_num > 0
AssertionError

**Comment by lucventurini** [comment]
Hi @swarbred 

I have tested this out and now the error should not be triggered. The issue was caused by transcripts being marked as having retained introns with a disrupted CDS in the early stages of Mikado (e.g. superlocus) and that flag not being cleared even after the transcripts were moved to loci where this inference would be invalid (e.g. the perceived retained intron ended up not overlapping of any intron in the final locus).
