### ISSUE TITLE
Error running mikado util stats

### ISSUE THREAD

**Issue by PeiwenLi** [EI-CoreBioinformatics/mikado#352]
Hi!
I am running Mikado/2.0rc4 to compute statistics using the `mikado util stats` command, following [this](https://mikado.readthedocs.io/en/latest/Tutorial/Adapting/#case-study-1-adapting-mikado-to-your-genome-of-interest) tutorial:
`mikado util stats ./RNA_seq/GCF_002910315.2_ASM291031v2_genomic_mod.gtf GCF_002910315.2_ASM291031v2.stats`

However, I got the following Assertion errors:

`Traceback (most recent call last):
  File "/home/peiwen/ENV/env-mikado/lib/python3.8/site-packages/Mikado/__init__.py", line 109, in main
    args.func(args)
  File "/home/peiwen/ENV/env-mikado/lib/python3.8/site-packages/Mikado/subprograms/util/stats.py", line 726, in launch
    calculator()
  File "/home/peiwen/ENV/env-mikado/lib/python3.8/site-packages/Mikado/subprograms/util/stats.py", line 334, in __call__
    self.parse_input()
  File "/home/peiwen/ENV/env-mikado/lib/python3.8/site-packages/Mikado/subprograms/util/stats.py", line 246, in parse_input
    self.__store_gene(current_gene)
  File "/home/peiwen/ENV/env-mikado/lib/python3.8/site-packages/Mikado/subprograms/util/stats.py", line 445, in __store_gene
    gene.finalize()
  File "/home/peiwen/ENV/env-mikado/lib/python3.8/site-packages/Mikado/loci/reference_gene.py", line 188, in finalize
    self.transcripts[tid].finalize()
  File "/home/peiwen/ENV/env-mikado/lib/python3.8/site-packages/Mikado/subprograms/util/stats.py", line 128, in finalize
    super().finalize()
  File "/home/peiwen/ENV/env-mikado/lib/python3.8/site-packages/Mikado/transcripts/transcript.py", line 1201, in finalize
    finalize(self)
  File "/home/peiwen/ENV/env-mikado/lib/python3.8/site-packages/Mikado/transcripts/transcript_methods/finalizing.py", line 688, in finalize
    _check_cdna_vs_utr(transcript)
  File "/home/peiwen/ENV/env-mikado/lib/python3.8/site-packages/Mikado/transcripts/transcript_methods/finalizing.py", line 164, in _check_cdna_vs_utr
    assert before or after, (exon, found)
AssertionError: ((23291038, 23291281), Interval(23289735, 23291281))
`

Could you please help?
Thanks,
Peiwen

**Comment by lucventurini** [comment]
Dear @PeiwenLi 

Apologies for the delay in replying but I was on holiday.
The problem you are finding seems related to incompatibility between the UTR and CDS, e.g. a CDS ending within a UTR segment, or between CDS and cDNA, e.g. the cDNA ending at one point and the CDS being slightly larger to accommodate truncated codons. I would bet on this second instance for this case. Specifically, there is the following exon:
23291038                    23291281

Which apparently is overlapping a *larger* CDS exon:
23289735                    23291281

This would be invalid because CDS exons must be strictly contained within cDNA exons.

I would recommend manually checking the input GTF to see whether this is the case. Usually running the GTF through `gffread` can solve some of these issues.

I hope this helps.

**Comment by PeiwenLi** [comment]
Thank you so much for your help!
Peiwen

**Comment by lucventurini** [comment]
Closing for now.
