### ISSUE TITLE
mikado serialise error when loading blast results

### ISSUE THREAD

**Issue by benedictcoombes** [EI-CoreBioinformatics/mikado#356]
Hi, I'm seeing an error during mikado serialise that I haven't been able to figure out and was hoping you could help.

mikado serialise --json-conf configuration.yaml --tsv split/merged_mikado.blast.tsv -p 8 --orfs mikado.bed

2021-01-11 08:44:44,959 - main - __init__.py:120 - ERROR - main - MainProcess - Mikado crashed, cause:
2021-01-11 08:44:44,959 - main - __init__.py:121 - ERROR - main - MainProcess - ('slength', 1853727, 1853727)
Traceback (most recent call last):
  File "/hpc-home/coombes/MiniConda/envs/annotation/lib/python3.7/site-packages/Mikado/__init__.py", line 106, in main
    args.func(args)
  File "/hpc-home/coombes/MiniConda/envs/annotation/lib/python3.7/site-packages/Mikado/subprograms/serialise.py", line 380, in serialise
    load_blast(args, logger)
  File "/hpc-home/coombes/MiniConda/envs/annotation/lib/python3.7/site-packages/Mikado/subprograms/serialise.py", line 124, in load_blast
    part_launcher(filenames)
  File "/hpc-home/coombes/MiniConda/envs/annotation/lib/python3.7/site-packages/Mikado/subprograms/serialise.py", line 55, in xml_launcher
    xml_serializer()
  File "/hpc-home/coombes/MiniConda/envs/annotation/lib/python3.7/site-packages/Mikado/serializers/blast_serializer/blast_serialiser.py", line 362, in __call__
    self.serialize()
  File "/hpc-home/coombes/MiniConda/envs/annotation/lib/python3.7/site-packages/Mikado/serializers/blast_serializer/blast_serialiser.py", line 346, in serialize
    self.__serialise_tabular()
  File "/hpc-home/coombes/MiniConda/envs/annotation/lib/python3.7/site-packages/Mikado/serializers/blast_serializer/blast_serialiser.py", line 350, in __serialise_tabular
    _serialise_tabular(self)
  File "/hpc-home/coombes/MiniConda/envs/annotation/lib/python3.7/site-packages/Mikado/serializers/blast_serializer/tab_serialiser.py", line 41, in _serialise_tabular
    parser(bname=fname)
  File "/hpc-home/coombes/MiniConda/envs/annotation/lib/python3.7/site-packages/Mikado/serializers/blast_serializer/tabular_utils.py", line 365, in parse_tab_blast
    data = sanitize_blast_data(data, queries, targets, qmult=qmult, tmult=tmult)
  File "/hpc-home/coombes/MiniConda/envs/annotation/lib/python3.7/site-packages/Mikado/serializers/blast_serializer/tabular_utils.py", line 233, in sanitize_blast_data
    assert ~(data[col].isna().any()), (col, data[data[col].isna()].shape[0], data.shape[0])
AssertionError: ('slength', 1853727, 1853727)

Here is the serialise.log file, showing that 0 queries were loaded:

2021-01-11 08:42:14,357 - serialiser - serialise.py:290 - INFO - setup - MainProcess - Command line: /hpc-home/coombes/MiniConda/envs/annotation/bin/mikado serialise --json-conf configuration.yaml --tsv split/merged_mikado.blast.tsv -p 8 --orfs mikado.bed
2021-01-11 08:42:14,357 - serialiser - serialise.py:296 - INFO - setup - MainProcess - Random seed: 0
2021-01-11 08:42:15,621 - serialiser - serialise.py:334 - INFO - setup - MainProcess - Using a sqlite database (location: /ei/projects/c/c38b7c13-1c82-4b59-ae07-b631556928a3/data/results/introgression_work/muticum_assembly/annotation/mikado/mikado.db)
2021-01-11 08:42:15,621 - serialiser - serialise.py:338 - INFO - setup - MainProcess - Requested 8 threads, forcing single thread: False
2021-01-11 08:42:15,621 - serialiser - serialise.py:140 - INFO - load_orfs - MainProcess - Starting to load ORF data
2021-01-11 08:42:26,848 - Bed12ParseWrapper-2 - bed12.py:1704 - INFO - run - Bed12ParseWrapper-2 - Started 0
2021-01-11 08:42:26,861 - Bed12ParseWrapper-3 - bed12.py:1704 - INFO - run - Bed12ParseWrapper-3 - Started 1
2021-01-11 08:42:26,876 - Bed12ParseWrapper-4 - bed12.py:1704 - INFO - run - Bed12ParseWrapper-4 - Started 2
2021-01-11 08:42:26,890 - Bed12ParseWrapper-5 - bed12.py:1704 - INFO - run - Bed12ParseWrapper-5 - Started 3
2021-01-11 08:42:26,904 - Bed12ParseWrapper-6 - bed12.py:1704 - INFO - run - Bed12ParseWrapper-6 - Started 4
2021-01-11 08:42:26,918 - Bed12ParseWrapper-7 - bed12.py:1704 - INFO - run - Bed12ParseWrapper-7 - Started 5
2021-01-11 08:42:26,933 - Bed12ParseWrapper-8 - bed12.py:1704 - INFO - run - Bed12ParseWrapper-8 - Started 6
2021-01-11 08:42:26,957 - Bed12ParseWrapper-9 - bed12.py:1704 - INFO - run - Bed12ParseWrapper-9 - Started 7
2021-01-11 08:43:20,040 - serialiser - orf.py:477 - INFO - __serialize_multiple_threads - MainProcess - Finished loading 241693 ORFs into the database
2021-01-11 08:43:24,198 - serialiser - serialise.py:152 - INFO - load_orfs - MainProcess - Finished loading ORF data
2021-01-11 08:43:24,363 - serialiser - serialise.py:107 - INFO - load_blast - MainProcess - Starting to load BLAST data
2021-01-11 08:43:24,365 - serialiser - blast_serialiser.py:78 - INFO - __init__ - MainProcess - Number of dedicated workers: 8
2021-01-11 08:43:47,555 - serialiser - blast_serialiser.py:244 - INFO - __serialize_targets - MainProcess - Started to serialise the targets
2021-01-11 08:43:58,366 - serialiser - blast_serialiser.py:279 - INFO - __serialize_targets - MainProcess - Loaded 654091 objects into the "target" table
2021-01-11 08:43:58,464 - serialiser - blast_serialiser.py:173 - INFO - __serialize_queries - MainProcess - Started to serialise the queries
2021-01-11 08:43:58,705 - serialiser - blast_serialiser.py:221 - INFO - __serialize_queries - MainProcess - Loaded 0 objects into the "query" table
2021-01-11 08:43:58,761 - serialiser - tab_serialiser.py:30 - INFO - _serialise_tabular - MainProcess - Creating a pool with 8 workers for analysing BLAST results
2021-01-11 08:44:04,184 - serialiser - tabular_utils.py:363 - INFO - parse_tab_blast - MainProcess - Reading split/merged_mikado.blast.tsv data

I wondered if there was a mismatch between the orfs and the transcripts or the blast output so I tried running without the orfs. According to the serialise.log, it loads the queries this time but still produces the error when loading the blast results:

mikado serialise --json-conf configuration.yaml --tsv split/merged_mikado.blast.tsv -p 8

2021-01-11 08:38:37,381 - main - __init__.py:120 - ERROR - main - MainProcess - Mikado crashed, cause:
2021-01-11 08:38:37,381 - main - __init__.py:121 - ERROR - main - MainProcess - ('slength', 1853727, 1853727)
Traceback (most recent call last):
  File "/hpc-home/coombes/MiniConda/envs/annotation/lib/python3.7/site-packages/Mikado/__init__.py", line 106, in main
    args.func(args)
  File "/hpc-home/coombes/MiniConda/envs/annotation/lib/python3.7/site-packages/Mikado/subprograms/serialise.py", line 380, in serialise
    load_blast(args, logger)
  File "/hpc-home/coombes/MiniConda/envs/annotation/lib/python3.7/site-packages/Mikado/subprograms/serialise.py", line 124, in load_blast
    part_launcher(filenames)
  File "/hpc-home/coombes/MiniConda/envs/annotation/lib/python3.7/site-packages/Mikado/subprograms/serialise.py", line 55, in xml_launcher
    xml_serializer()
  File "/hpc-home/coombes/MiniConda/envs/annotation/lib/python3.7/site-packages/Mikado/serializers/blast_serializer/blast_serialiser.py", line 362, in __call__
    self.serialize()
  File "/hpc-home/coombes/MiniConda/envs/annotation/lib/python3.7/site-packages/Mikado/serializers/blast_serializer/blast_serialiser.py", line 346, in serialize
    self.__serialise_tabular()
  File "/hpc-home/coombes/MiniConda/envs/annotation/lib/python3.7/site-packages/Mikado/serializers/blast_serializer/blast_serialiser.py", line 350, in __serialise_tabular
    _serialise_tabular(self)
  File "/hpc-home/coombes/MiniConda/envs/annotation/lib/python3.7/site-packages/Mikado/serializers/blast_serializer/tab_serialiser.py", line 41, in _serialise_tabular
    parser(bname=fname)
  File "/hpc-home/coombes/MiniConda/envs/annotation/lib/python3.7/site-packages/Mikado/serializers/blast_serializer/tabular_utils.py", line 365, in parse_tab_blast
    data = sanitize_blast_data(data, queries, targets, qmult=qmult, tmult=tmult)
  File "/hpc-home/coombes/MiniConda/envs/annotation/lib/python3.7/site-packages/Mikado/serializers/blast_serializer/tabular_utils.py", line 233, in sanitize_blast_data
    assert ~(data[col].isna().any()), (col, data[data[col].isna()].shape[0], data.shape[0])
AssertionError: ('slength', 1853727, 1853727)

serialise.log when no orfs are given:
2021-01-11 08:37:25,122 - serialiser - serialise.py:290 - INFO - setup - MainProcess - Command line: /hpc-home/coombes/MiniConda/envs/annotation/bin/mikado serialise --json-conf configuration.yaml --tsv split/merged_mikado.blast.tsv -p 8
2021-01-11 08:37:25,122 - serialiser - serialise.py:296 - INFO - setup - MainProcess - Random seed: 0
2021-01-11 08:37:26,409 - serialiser - serialise.py:334 - INFO - setup - MainProcess - Using a sqlite database (location: /ei/projects/c/c38b7c13-1c82-4b59-ae07-b631556928a3/data/results/introgression_work/muticum_assembly/annotation/mikado/mikado.db)
2021-01-11 08:37:26,409 - serialiser - serialise.py:338 - INFO - setup - MainProcess - Requested 8 threads, forcing single thread: False
2021-01-11 08:37:26,409 - serialiser - serialise.py:154 - INFO - load_orfs - MainProcess - No ORF data provided, skipping
2021-01-11 08:37:26,409 - serialiser - serialise.py:107 - INFO - load_blast - MainProcess - Starting to load BLAST data
2021-01-11 08:37:26,409 - serialiser - blast_serialiser.py:78 - INFO - __init__ - MainProcess - Number of dedicated workers: 8
2021-01-11 08:37:30,391 - serialiser - blast_serialiser.py:244 - INFO - __serialize_targets - MainProcess - Started to serialise the targets
2021-01-11 08:37:41,486 - serialiser - blast_serialiser.py:279 - INFO - __serialize_targets - MainProcess - Loaded 654091 objects into the "target" table
2021-01-11 08:37:41,584 - serialiser - blast_serialiser.py:173 - INFO - __serialize_queries - MainProcess - Started to serialise the queries
2021-01-11 08:37:49,108 - serialiser - blast_serialiser.py:221 - INFO - __serialize_queries - MainProcess - Loaded 465094 objects into the "query" table
2021-01-11 08:37:49,214 - serialiser - tab_serialiser.py:30 - INFO - _serialise_tabular - MainProcess - Creating a pool with 8 workers for analysing BLAST results
2021-01-11 08:37:54,794 - serialiser - tabular_utils.py:363 - INFO - parse_tab_blast - MainProcess - Reading split/merged_mikado.blast.tsv data

Many thanks for your help,

Ben.

**Comment by lucventurini** [comment]
Hi @benedictcoombes 

Thank you for reporting this bug. This error *seems* to be related to your input TSV: specifically, Mikado is complaining that the "slength" column is populated only by NaN values. As this column is necessary, Mikado crashes.

May I ask how the input TSV file was generated? As per the CLI help, it should have the following fields:

```
BLAST file(s) to parse. They can be provided in three ways:
- a comma-separated list
- as a base folder
- using bash-like name expansion (*,?, etc.).
   - In this  case, you have to enclose the filename pattern in double quotes.

Multiple folders/file patterns can be given, separated by a comma. BLAST files must be either
of two formats:
- BLAST XML
- BLAST tabular format, with the following **custom** fields:
   qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore ppos btop
```

Kind regards,

**Comment by benedictcoombes** [comment]
Hi Luca, thanks for getting back to me.

I generated the tsv using the following command:
blastx -max_target_seqs 5 -num_threads 16 -query $query -outfmt "6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore ppos btop" -db $protein_db -evalue 0.000001 > ${prefix}_mikado.blast.tsv

Here is the top of my blast output file:

tr_TRINITY_GG_44698_c0_g2_i1.path3	tr|A0A446VIM8|A0A446VIM8_TRITD	68.627	51	12	1	65	217	712	758	5.12e-15	72.0	76.47	3REQK1SF5QW3VISLGE1VM14K-C-A-E-2SGIVDG5RS1
tr_TRINITY_GG_59394_c0_g1_i1.path1	tr|A0A453DME3|A0A453DME3_AEGTS	89.071	183	20	0	623	75	219	401	1.72e-113	333	91.80	MLSL4LM19HQ9NK18HP6RG3VG4SP1GD10VM1DG1TA1AP4IT4GD11MV28FSRA32QE7
tr_TRINITY_GG_7446_c2_g1_i1.path1	tr|A0A446JL96|A0A446JL96_TRITD	76.923	182	23	4	173	718	6	168	1.27e-88	270	80.22	MIASAR6RHASSPA-*-VLGNQHCLALYI1VLEPS-S-Y-Y-F-A-A-1TP6SG13S-I-R-1ELTHAP1IP1ETV-V-*-A-V-E-G-2SF17RK91
tr_TRINITY_GG_7446_c2_g1_i1.path1	tr|A0A3B5YTT8|A0A3B5YTT8_WHEAT	76.923	182	23	4	173	718	6	168	1.27e-88	270	80.22	MIASAR6RHASSPA-*-VLGNQHCLALYI1VLEPS-S-Y-Y-F-A-A-1TP6SG13S-I-R-1ELTHAP1IP1ETV-V-*-A-V-E-G-2SF17RK91
tr_TRINITY_GG_7446_c2_g1_i1.path1	tr|A0A446ILK8|A0A446ILK8_TRITD	82.895	152	18	2	263	718	61	204	1.51e-78	245	83.55	1TP7S-1AFRL1SRAWVPGSRTLPHPEASPIARD1EKTQ1H-I-R-E-V-V-*-10AP2FL102
tr_TRINITY_GG_7446_c2_g1_i1.path1	tr|A0A446ILK8|A0A446ILK8_TRITD	74.468	47	5	2	105	224	1	47	2.90e-11	66.6	78.72	1LP3-W3IS13-R-M-G-M-A-AASWF1HD14
tr_TRINITY_GG_7446_c2_g1_i1.path1	tr|A0A3B5ZPD1|A0A3B5ZPD1_WHEAT	100.000	107	0	0	398	718	1	107	1.22e-72	226	100.00	107
tr_TRINITY_GG_7446_c2_g1_i1.path1	tr|A0A452XV88|A0A452XV88_AEGTS	100.000	107	0	0	398	718	1	107	1.22e-72	226	100.00	107
st_STRG.27491.1	tr|A0A453EUW7|A0A453EUW7_AEGTS	89.474	19	2	0	386	442	1	19	1.44e-09	46.6	94.74	16VI1NK
st_STRG.27491.1	tr|A0A453EUW7|A0A453EUW7_AEGTS	88.889	18	2	0	430	483	16	33	1.44e-09	36.2	88.89	1CI10HR5

Many thanks,

Ben.

**Comment by lucventurini** [comment]
Hi @benedictcoombes 

Revising the code I realised that the bug you are encountering *has already been fixed some months ago* (in 818a601f01b08cf2e425975aa7cab3e0196bf698). Could you please clone from the most recent `master` and retry?

Many thanks!

**Comment by benedictcoombes** [comment]
Hi Luca,

That fixed my problem. Mikado serialise finished running and I now have the results from mikado pick. serialise.log still says 0 queries loaded but I'm assuming that's okay given that there weren't downstream errors?

Thanks for your help,

Ben.

**Comment by lucventurini** [comment]
Hi @benedictcoombes 

1- You can check quickly whether the BLAST results have been actually loaded in two ways:
    - the "metrics.tsv" file associated with the pick output has some columns associated with the BLAST data, e.g. blast_score, bits, etc. If they are all empty there is a problem.
    - relatedly, using sqlite3 on the mikado.db, this command: `select count(*) from hit` will tell you how many BLAST lines have been loaded.
2- In case they have not been loaded correctly, two options:
   - delete the database or launch `mikado serialise` with `--force`
   - Drop the `hit` and `hsp` tables before relaunching Mikado.

I hope this helps.

**Comment by benedictcoombes** [comment]
Hi Luca, I checked the metrics.tsv file and the blast columns are not empty, so looks like it worked!

Many thanks,

Ben.

**Comment by lucventurini** [comment]
Hi @benedictcoombes 

Excellent, thank you for letting me know! I will close the issue now.

Glad to be helpful.
