### ISSUE TITLE
[BUG] Mikado crashes due to a bug in padding

### ISSUE THREAD

**Issue by lucventurini** [EI-CoreBioinformatics/mikado#395]
Error:

```python
2021-03-25 21:37:49,669 - ptg000014l:4535909-4544907 - loci_processer.py:272 - ERROR - analyse_locus - LociProcesser-13 - Invalid CDS length: 2260 % 3 = 1 (536-2795, 0)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/Mikado/picking/loci_processer.py", line 270, in analyse_locus
    stranded_locus.define_loci()
  File "/usr/local/lib/python3.8/dist-packages/Mikado/loci/superlocus.py", line 1168, in define_loci
    self.define_alternative_splicing()
  File "/usr/local/lib/python3.8/dist-packages/Mikado/loci/superlocus.py", line 1312, in define_alternative_splicing
    self.loci[lid].finalize_alternative_splicing()
  File "/usr/local/lib/python3.8/dist-packages/Mikado/loci/locus.py", line 213, in finalize_alternative_splicing
    failed = self.launch_padding()
  File "/usr/local/lib/python3.8/dist-packages/Mikado/loci/locus.py", line 266, in launch_padding
    templates = self.pad_transcripts(backup)
  File "/usr/local/lib/python3.8/dist-packages/Mikado/loci/locus.py", line 976, in pad_transcripts
    new_transcript = pad_transcript(backup[tid],
  File "/usr/local/lib/python3.8/dist-packages/Mikado/transcripts/pad.py", line 79, in pad_transcript
    transcript = enlarge_orfs(transcript, backup, seq, upstream, downstream, logger)
  File "/usr/local/lib/python3.8/dist-packages/Mikado/transcripts/pad.py", line 380, in enlarge_orfs
    raise InvalidTranscript(orf.invalid_reason)
Mikado.exceptions.InvalidTranscript: Invalid CDS length: 2260 % 3 = 1 (536-2795, 0)
```

This seems to be triggered by an invalid operation during the expansion of the ORF.

**Comment by ljyanesm** [comment]
Also see:

```python
Process LociProcesser-4:
Traceback (most recent call last):
  File "/python/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/mikado/Mikado/picking/loci_processer.py", line 496, in run
    accumulator = serialise_locus(
  File "/mikado/Mikado/picking/_loci_serialiser.py", line 27, in serialise_locus
    assert sublocus.scores_calculated is True, (sublocus.id, sublocus.scores_calculated)
AssertionError: ('sublocus:ptg000014l-:4540629-4544907.multi', False)
```
