### ISSUE TITLE
Error in rule mikado_prepare

### ISSUE THREAD

**Issue by louphey** [EI-CoreBioinformatics/mikado#397]
Hello,

I am currently running the following command "daijin mikado Dmelanogaster/mikado.yaml"  following the tutorial <https://mikado.readthedocs.io/en/latest/Tutorial/Daijin_tutorial/#step-3-running-the-mikado-steps>

but I get the following error.

Error in rule mikado_prepare:
    jobid: 4
    output: Dmelanogaster/5-mikado/mikado_prepared.gtf, Dmelanogaster/5-mikado/mikado_prepared.fasta
    log: Dmelanogaster/5-mikado/mikado_prepare.log (check log file(s) for error message)
    shell:
         mikado prepare -l Dmelanogaster/5-mikado/mikado_prepare.log --start-method=spawn --fasta=Dmelanogaster/0-reference/genome.fa.gz --configuration=/path/to/Dmelanogaster/daijin.2021-03-28_00:34:55.yaml -od Dmelanogaster/5-mikado 2>&1
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Could you please help with that?

**Comment by ljyanesm** [comment]
Dear @louphey,

Could you share the contents of the `Dmelanogaster/5-mikado/mikado_prepare.log` file? It will contain some relevant details to help identify the issue.

Many thanks,

**Comment by louphey** [comment]
Hi, @ljyanesm 
The following is the contents of the Dmelanogaster/5-mikado/mikado_prepare.log file

2021-03-28 00:34:57,154 - prepare - prepare.py:177 - INFO - setup - MainProcess - Mikado version: 2.2.3
2021-03-28 00:34:57,154 - prepare - prepare.py:178 - INFO - setup - MainProcess - Command line: /home/app/miniconda2/envs/mikado/bin/mikado prepare -l Dmelanogaster/5-mikado/mikado_prepare.log --start-method=spawn --fasta=Dmelanogaster/0-reference/genome.fa.gz --configuration=/home/lofy/temp/aaa/Dmelanogaster/daijin.2021-03-28_00:34:55.yaml -od Dmelanogaster/5-mikado
2021-03-28 00:34:57,154 - prepare - prepare.py:179 - INFO - setup - MainProcess - Random seed: 0
2021-03-28 00:34:57,161 - prepare - prepare.py:630 - INFO - prepare - MainProcess - Output dir: Dmelanogaster/5-mikado. Output GTF: Dmelanogaster/5-mikado/mikado_prepared.gtf. Output Fasta: Dmelanogaster/5-mikado/mikado_prepared.fasta
2021-03-28 00:34:57,161 - prepare - prepare.py:634 - INFO - prepare - MainProcess - Loading reference file
2021-03-28 00:34:57,163 - prepare - prepare.py:636 - INFO - prepare - MainProcess - Finished loading genome file
2021-03-28 00:34:57,163 - prepare - prepare.py:637 - INFO - prepare - MainProcess - Started loading exon lines
2021-03-28 00:34:57,163 - prepare - prepare.py:441 - INFO - _load_exon_lines_multi - MainProcess - Starting to load lines from 12 files (using 10 processes)
2021-03-28 00:34:59,484 - prepare - prepare.py:501 - INFO - _load_exon_lines_multi - MainProcess - Finished parsing all input files
2021-03-28 00:34:59,539 - prepare - prepare.py:531 - INFO - load_exon_lines - MainProcess - Finished loading lines from 12 files
2021-03-28 00:34:59,543 - prepare - prepare.py:646 - INFO - prepare - MainProcess - Finished loading exon lines
2021-03-28 00:34:59,550 - prepare - prepare.py:685 - ERROR - prepare - MainProcess - [Errno 2] No such file or directory: 'Dmelanogaster/5-mikado/mikado_shelf_00000.db'
Traceback (most recent call last):
  File "/home/app/miniconda2/envs/mikado/lib/python3.8/site-packages/Mikado/preparation/prepare.py", line 669, in prepare
    shelves = dict((shelf_name, open(shelf_name, "rb")) for shelf_name in shelve_table["shelf"].unique())
  File "/home/app/miniconda2/envs/mikado/lib/python3.8/site-packages/Mikado/preparation/prepare.py", line 669, in <genexpr>
    shelves = dict((shelf_name, open(shelf_name, "rb")) for shelf_name in shelve_table["shelf"].unique())
FileNotFoundError: [Errno 2] No such file or directory: 'Dmelanogaster/5-mikado/mikado_shelf_00000.db'
2021-03-28 00:34:59,552 - prepare - prepare.py:688 - ERROR - prepare - MainProcess - Mikado has encountered an error, exiting
2021-03-28 00:34:59,553 - prepare - prepare.py:705 - ERROR - prepare - MainProcess - Mikado prepare has encountered a fatal error. Please check the logs and, if there is a bug,report it to https://github.com/EI-CoreBioinformatics/mikado/issues

**Comment by ljyanesm** [comment]
Dear @louphey,

Thank you for reporting this issue. I can confirm this is reproducible in the current release 2.2.3, this issue has been resolved already in branch issue-395-pick-pad-crash. The changes in that branch will be released as soon as possible.

Thank you again for bringing this to attention
