### ISSUE TITLE
Cannot run Class2 in Daijin pipeline

### ISSUE THREAD

**Issue by louphey** [EI-CoreBioinformatics/mikado#401]
Hi,

I'm using mikado v2.2.4.
I did not find out  `​class = [ "",] ` in the `[asm_methods]` section of daijin.toml after configuring Daijin according to  [https://mikado.readthedocs.io/en/stable/Tutorial/Daijin_tutorial/](url)
So I added `​class = [ "",] ` into the daijin.toml, then  run `daijin assemble --cores 30 daijin.toml`. 
Then I got the following error message.

2021-04-11 23:25:11,507 - main - __main__.py:79 - ERROR - main - MainProcess - Daijin crashed, cause:
2021-04-11 23:25:11,507 - main - __main__.py:80 - ERROR - main - MainProcess - {'asm_methods': {'class': ['Unknown field.']}}
Traceback (most recent call last):
  File "/home/app/miniconda2/envs/mikado/lib/python3.8/site-packages/Mikado/daijin/__main__.py", line 70, in main
    args.func(args)
  File "/home/app/miniconda2/envs/mikado/lib/python3.8/site-packages/Mikado/daijin/assemble.py", line 53, in assemble_transcripts_pipeline
    _ = DaijinConfiguration.Schema().load(doc)
  File "/home/app/miniconda2/envs/mikado/lib/python3.8/site-packages/marshmallow_dataclass/__init__.py", line 578, in load
    all_loaded = super().load(data, many=many, **kwargs)
  File "/home/app/miniconda2/envs/mikado/lib/python3.8/site-packages/marshmallow/schema.py", line 725, in load
    return self._do_load(
  File "/home/app/miniconda2/envs/mikado/lib/python3.8/site-packages/marshmallow/schema.py", line 907, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {'asm_methods': {'class': ['Unknown field.']}}

**Comment by ljyanesm** [comment]
Dear @louphey,

I have just created a branch where this issue is addressed, the parameter is now be named 'class2'

**Comment by lucventurini** [comment]
Thank you @ljyanesm for picking this up.

We probably need to update the documentation as well.

**Comment by ljyanesm** [comment]
I'll have a look if there's anything left to update there, I've just added a commit with some changes to the docs too, but haven't reviewed the text carefully yet
