### ISSUE TITLE
'list' object has no attribute 'finalize'

### ISSUE THREAD

**Issue by francicco** [EI-CoreBioinformatics/mikado#409]
Hi,

running mikado pick I'm getting this error:

```
Traceback (most recent call last):
  File "/sw/lang/anaconda.3.8-2020.07/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/work/tk19812/software/mikado-2.3.0/venv/lib/python3.8/site-packages/Mikado/picking/loci_processer.py", line 492, in run
    stranded_loci = self.analyse_locus(slocus, counter)
  File "/work/tk19812/software/mikado-2.3.0/venv/lib/python3.8/site-packages/Mikado/picking/loci_processer.py", line 270, in analyse_locus
    stranded_locus.define_loci()
  File "/work/tk19812/software/mikado-2.3.0/venv/lib/python3.8/site-packages/Mikado/loci/superlocus.py", line 1168, in define_loci
    self.define_alternative_splicing()
  File "/work/tk19812/software/mikado-2.3.0/venv/lib/python3.8/site-packages/Mikado/loci/superlocus.py", line 1311, in define_alternative_splicing
    self.loci[lid].add_transcript_to_locus(self.transcripts[tid])
  File "/work/tk19812/software/mikado-2.3.0/venv/lib/python3.8/site-packages/Mikado/loci/locus.py", line 543, in add_transcript_to_locus
    is_alternative, ccode, _ = self.is_alternative_splicing(transcript)
  File "/work/tk19812/software/mikado-2.3.0/venv/lib/python3.8/site-packages/Mikado/loci/locus.py", line 881, in is_alternative_splicing
    main_result, _ = Assigner.compare(other._selected_orf_transcript,
  File "/work/tk19812/software/mikado-2.3.0/venv/lib/python3.8/site-packages/Mikado/scales/assignment/assigner.py", line 819, in compare
    return c_compare(prediction,
  File "Mikado/scales/contrast.pyx", line 239, in Mikado.scales.contrast.compare
  File "Mikado/scales/contrast.pyx", line 288, in Mikado.scales.contrast.compare
AttributeError: 'list' object has no attribute 'finalize'
```

Is there a problem with the installation?
Cheers
F

**Comment by ljyanesm** [comment]
Dear @francicco,

It does not seem to be an issue with the installation but with some internal workings in Mikado.

Could extract a minimal reproducible example of this behaviour so I can have a look?

Many thanks

**Comment by francicco** [comment]
I think it was my mistake. I fixed it
Cheers
F
