### ISSUE TITLE
Mikado serialise sql3 error

### ISSUE THREAD

**Issue by AlexdeMendoza** [EI-CoreBioinformatics/mikado#429]
Hi, I have used Mikado several times successfully on the same server/installation, but now I am encountering a new error on the serialise step that I do not really understand where it comes from. The command I am using is: 
`mikado serialise --procs 1 --json-conf configuration.yaml --tsv mikado.diamond.tsv --orfs mikado_prepared.fasta.transdecoder.bed --blast_targets uniprot_sprot.fasta --transcripts mikado_prepared.fasta --junctions portcullis_filtered.pass.junctions.bed`

And the error I get is: 
```Mikado crashed, cause:
(sqlite3.IntegrityError) UNIQUE constraint failed: query.query_name
[SQL: INSERT INTO "query" (query_name, query_length) VALUES (?, ?)]
[parameters: (('Scaffold1', 2076), ('Scaffold1', 5901), ('Scaffold1', 5316), ('Scaffold1', 1122), ('Scaffold1', 1689), ('Scaffold1', 486), ('Scaffold1', 528), ('Scaffold1', 912)  ... displaying 10 of 6716 total bound parameter sets ...  ('Scaffold990', 882), ('Scaffold992', 1629))]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
```

It seems to be looking for unique query names on the diamond blastx .tsv file, but I don't think that was necessary on other runs I did before. Any idea on what must be happening? 

Thanks in advance for your help. 

Best,

Alex

**Comment by AlexdeMendoza** [comment]
Hi Luc, 

```Mikado crashed, cause:
(sqlite3.IntegrityError) UNIQUE constraint failed: query.query_name
[SQL: INSERT INTO "query" (query_name, query_length) VALUES (?, ?)]
[parameters: (('Scaffold1', 2076), ('Scaffold1', 5901), ('Scaffold1', 5316), ('Scaffold1', 1122), ('Scaffold1', 1689), ('Scaffold1', 486), ('Scaffold1', 528), ('Scaffold1', 912)  ... displaying 10 of 6716 total bound parameter sets ...  ('Scaffold990', 882), ('Scaffold992', 1629))]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
Traceback (most recent call last):
  File "/data/home/btx717/miniconda2/envs/mikado/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1256, in _execute_context
    self.dialect.do_executemany(
  File "/data/home/btx717/miniconda2/envs/mikado/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 605, in do_executemany
    cursor.executemany(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: query.query_name

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/home/btx717/miniconda2/envs/mikado/lib/python3.8/site-packages/Mikado-2.3.0-py3.8-linux-x86_64.egg/Mikado/__main__.py", line 68, in main
    args.func(args)
  File "/data/home/btx717/miniconda2/envs/mikado/lib/python3.8/site-packages/Mikado-2.3.0-py3.8-linux-x86_64.egg/Mikado/subprograms/serialise.py", line 384, in serialise
    load_blast(mikado_configuration, logger)
  File "/data/home/btx717/miniconda2/envs/mikado/lib/python3.8/site-packages/Mikado-2.3.0-py3.8-linux-x86_64.egg/Mikado/subprograms/serialise.py", line 159, in load_blast
    part_launcher(filenames)
  File "/data/home/btx717/miniconda2/envs/mikado/lib/python3.8/site-packages/Mikado-2.3.0-py3.8-linux-x86_64.egg/Mikado/subprograms/serialise.py", line 87, in xml_launcher
    xml_serializer()
  File "/data/home/btx717/miniconda2/envs/mikado/lib/python3.8/site-packages/Mikado-2.3.0-py3.8-linux-x86_64.egg/Mikado/serializers/blast_serializer/blast_serialiser.py", line 377, in __call__
    self.serialize()
  File "/data/home/btx717/miniconda2/envs/mikado/lib/python3.8/site-packages/Mikado-2.3.0-py3.8-linux-x86_64.egg/Mikado/serializers/blast_serializer/blast_serialiser.py", line 338, in serialize
    self.queries, self.targets = self.__serialise_sequences()
  File "/data/home/btx717/miniconda2/envs/mikado/lib/python3.8/site-packages/Mikado-2.3.0-py3.8-linux-x86_64.egg/Mikado/serializers/blast_serializer/blast_serialiser.py", line 315, in __serialise_sequences
    queries = self.__serialize_queries(queries)
  File "/data/home/btx717/miniconda2/envs/mikado/lib/python3.8/site-packages/Mikado-2.3.0-py3.8-linux-x86_64.egg/Mikado/serializers/blast_serializer/blast_serialiser.py", line 222, in __serialize_queries
    self.engine.execute(Query.__table__.insert(), objects)
  File "/data/home/btx717/miniconda2/envs/mikado/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2235, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/data/home/btx717/miniconda2/envs/mikado/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/data/home/btx717/miniconda2/envs/mikado/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/data/home/btx717/miniconda2/envs/mikado/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "/data/home/btx717/miniconda2/envs/mikado/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/data/home/btx717/miniconda2/envs/mikado/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/data/home/btx717/miniconda2/envs/mikado/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/data/home/btx717/miniconda2/envs/mikado/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1256, in _execute_context
    self.dialect.do_executemany(
  File "/data/home/btx717/miniconda2/envs/mikado/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 605, in do_executemany
    cursor.executemany(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: query.query_name
[SQL: INSERT INTO "query" (query_name, query_length) VALUES (?, ?)]
[parameters: (('Scaffold1', 2076), ('Scaffold1', 5901), ('Scaffold1', 5316), ('Scaffold1', 1122), ('Scaffold1', 1689), ('Scaffold1', 486), ('Scaffold1', 528), ('Scaffold1', 912)  ... displaying 10 of 6716 total bound parameter sets ...  ('Scaffold990', 882), ('Scaffold992', 1629))]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
```

This is the whole thing. One of the gtfs used as input has gene names that contain "|", such as `meta1_XM_032980676.1|Scaffold2418|+`. So it could be that the program is just taking the `meta1_XM_032980676.1` and therefore causing this issue with naming repeated?

**Comment by AlexdeMendoza** [comment]
Dear Luc, we figured out that the problem was the "|" in the transcript names that broke the program, we changed that and it run. Thanks for your help. A.
