### ISSUE TITLE
Error with mikado serialise: 'Engine' object has no attribute 'cursor'

### ISSUE THREAD

**Issue by bbista** [EI-CoreBioinformatics/mikado#450]
Hello,
I am having trouble with the mikado serialize step. I get this error every time:

 mikado serialise --json-conf configuration.yaml --xml mikado_prepared.blast.tsv --orfs mikado.orfs.gff3 --junctions portcullis_filtered.pass.junctions.bed -bt /uniprot/TSEprotein.faa

Mikado crashed, cause:
'Engine' object has no attribute 'cursor'
Traceback (most recent call last):
  File "/home/bbista/.local/lib/python3.9/site-packages/Mikado/__main__.py", line 68, in main
    args.func(args)
  File "/home/bbista/.local/lib/python3.9/site-packages/Mikado/subprograms/serialise.py", line 383, in serialise
    load_orfs(mikado_configuration, logger)
  File "/home/bbista/.local/lib/python3.9/site-packages/Mikado/subprograms/serialise.py", line 183, in load_orfs
    serializer()
  File "/home/bbista/.local/lib/python3.9/site-packages/Mikado/serializers/orf.py", line 486, in __call__
    self.serialize()
  File "/home/bbista/.local/lib/python3.9/site-packages/Mikado/serializers/orf.py", line 461, in serialize
    self.load_fasta()
  File "/home/bbista/.local/lib/python3.9/site-packages/Mikado/serializers/orf.py", line 260, in load_fasta
    cache = pd.read_sql_table("query", self.engine, index_col="query_name", columns=["query_name", "query_id"])
  File "/home/bbista/.local/lib/python3.9/site-packages/pandas/io/sql.py", line 385, in read_sql_table
    if not pandas_sql.has_table(table_name):
  File "/home/bbista/.local/lib/python3.9/site-packages/pandas/io/sql.py", line 2863, in has_table
    return len(self.execute(query, [name]).fetchall()) > 0
  File "/home/bbista/.local/lib/python3.9/site-packages/pandas/io/sql.py", line 2670, in execute
    cur = self.con.cursor()
AttributeError: 'Engine' object has no attribute 'cursor'

The log file for serialize looks like this:
2024-02-26 07:55:35,513 - serialise - serialise.py:321 - INFO - setup - MainProcess - Mikado version: 2.3.4
2024-02-26 07:55:35,513 - serialise - serialise.py:322 - INFO - setup - MainProcess - Command line: /home/bbista/.local/bin/mikado serialise --json-conf configuration.yaml --xml mikado_prepared.blast.tsv --orfs mikado.orfs.gff3 --junctions /work/LAS/nvalenzu-lab/bbista/ASP_final_annot/portcullis_out_ASP/3-filt/portcullis_filtered.pass.junctions.bed -bt /work/LAS/nvalenzu-lab/bbista/uniprot/TSEprotein.faa
2024-02-26 07:55:35,526 - serialise - serialise.py:332 - INFO - setup - MainProcess - Random seed: 0
2024-02-26 07:55:35,526 - serialise - serialise.py:345 - INFO - setup - MainProcess - Using a sqlite database (location: mikado.db)
2024-02-26 07:55:35,526 - serialise - serialise.py:348 - INFO - setup - MainProcess - Requested 1 threads, forcing single thread: False
2024-02-26 07:55:35,526 - serialise - serialise.py:176 - INFO - load_orfs - MainProcess - Starting to load ORF data

I am using  Mikado v2.3.4 installed using the following steps:

mamba env create -f environment.yml

pip wheel -w dist .
pip install dist/*whl

I only have issues with the serialise part.

Any help is greatly appreaciated.

Best,
bbista

**Comment by jasonshiller** [comment]
@bbista I have the same problem. Did you manage to solve this?

**Comment by bbista** [comment]
@jasonshiller I did not solve it at all. I work in an HPC cluster and I just installed mikado in a different HPC cluster where I do not get this error. Only advice I can give you is to try a different machine.

**Comment by singhua-agri** [comment]
I encountered the same problem as @jasonshiller and @bbista. I installed Mikado using Conda, and the version of Pandas provided was 2.2.x, while the version of SQLAlchemy was 1.4.x. The incompatibility between these two versions is documented https://github.com/pandas-dev/pandas/issues/57049. I downgraded Pandas, and Mikado ran successfully afterward.

**Comment by gemygk** [comment]
Apologies @bbista @jasonshiller @VitaxZhang 

I wanted to let you know that I added additional methods for installing Mikado (via Docker, Singularity, and Conda/Mamba) a couple of months ago. Please refer to the updated [installation steps here](https://github.com/EI-CoreBioinformatics/mikado?tab=readme-ov-file#installation) for detailed installation steps.

Please let me know how it goes.

**Comment by desmodus1984** [comment]
Hi, I installed mikado in an environment with all the requirements:
and I still got the same error:

```
Mikado crashed, cause:
'Engine' object has no attribute 'cursor'
Traceback (most recent call last):
  File "/data/common/juanpablo.aguilar/apps/Miniforge3/envs/mikado/lib/python3.12/site-packages/Mikado/__main__.py", line 68, in main
    args.func(args)
  File "/data/common/juanpablo.aguilar/apps/Miniforge3/envs/mikado/lib/python3.12/site-packages/Mikado/subprograms/serialise.py", line 383, in serialise
    load_orfs(mikado_configuration, logger)
  File "/data/common/juanpablo.aguilar/apps/Miniforge3/envs/mikado/lib/python3.12/site-packages/Mikado/subprograms/serialise.py", line 183, in load_orfs
    serializer()
  File "/data/common/juanpablo.aguilar/apps/Miniforge3/envs/mikado/lib/python3.12/site-packages/Mikado/serializers/orf.py", line 486, in __call__
    self.serialize()
  File "/data/common/juanpablo.aguilar/apps/Miniforge3/envs/mikado/lib/python3.12/site-packages/Mikado/serializers/orf.py", line 461, in serialize
    self.load_fasta()
  File "/data/common/juanpablo.aguilar/apps/Miniforge3/envs/mikado/lib/python3.12/site-packages/Mikado/serializers/orf.py", line 260, in load_fasta
    cache = pd.read_sql_table("query", self.engine, index_col="query_name", columns=["query_name", "query_id"])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/common/juanpablo.aguilar/apps/Miniforge3/envs/mikado/lib/python3.12/site-packages/pandas/io/sql.py", line 385, in read_sql_table
    if not pandas_sql.has_table(table_name):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/common/juanpablo.aguilar/apps/Miniforge3/envs/mikado/lib/python3.12/site-packages/pandas/io/sql.py", line 2865, in has_table
    return len(self.execute(query, [name]).fetchall()) > 0
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/common/juanpablo.aguilar/apps/Miniforge3/envs/mikado/lib/python3.12/site-packages/pandas/io/sql.py", line 2672, in execute
    cur = self.con.cursor()
          ^^^^^^^^^^^^^^^
AttributeError: 'Engine' object has no attribute 'cursor'
```

This is the script:
```
mikado serialise \
 -p 60 --start-method spawn \
 --transcripts mikado_prepared.fasta \
 --json-conf conf.yaml \
 --genome_fai Lepwed.softmasked.fasta.fai \
 --junctions 3-filt/portcullis_filtered.pass.junctions.bed \
 --tsv LW3_blast_results.tsv \
 --blast-targets uniprot_sprot.fasta \
 --max-target-seqs 5 \
 --orfs mikado_prepared.fasta.TD2.bed \
 --log mikado_serialise.log
```

All the files are in the directory

Despite getting an error, I was able to run prepare, but then when I tried serialize, it failed horribly
```
Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: failed

CondaVerificationError: The package for libboost-headers located at /data/common/juanpablo.aguilar/apps/Miniforge3/pkgs/libboost-headers-1.84.0-ha770c72_7
appears to be corrupted. The path 'include/boost/accumulators/accumulators.hpp'
specified in the package manifest cannot be found.

CondaVerificationError: The package for libboost-headers located at /data/common/juanpablo.aguilar/apps/Miniforge3/pkgs/libboost-headers-1.84.0-ha770c72_7
appears to be corrupted. The path 'include/boost/accumulators/accumulators_fwd.hpp'
specified in the package manifest cannot be found.

CondaVerificationError: The package for libboost-headers located at /data/common/juanpablo.aguilar/apps/Miniforge3/pkgs/libboost-headers-1.84.0-ha770c72_7
appears to be corrupted. The path 'include/boost/accumulators/framework/accumulator_base.hpp'
specified in the package manifest cannot be found.

CondaVerificationError: The package for libboost-headers located at /data/common/juanpablo.aguilar/apps/Miniforge3/pkgs/libboost-headers-1.84.0-ha770c72_7
appears to be corrupted. The path 'include/boost/accumulators/framework/accumulator_concept.hpp'
specified in the package manifest cannot be found.

CondaVerificationError: The package for libboost-headers located at /data/common/juanpablo.aguilar/apps/Miniforge3/pkgs/libboost-headers-1.84.0-ha770c72_7
appears to be corrupted. The path 'include/boost/accumulators/framework/accumulators/droppable_accumulator.hpp'
specified in the package manifest cannot be found.
```
Since the problem seems to be libboost, I installed it 
 conda install conda-forge::libboost-headers

and it still failed serialize.

Why is it not running?

Also cloning as stated doesn't work:
```
 git clone git@github.com:EI-CoreBioinformatics/mikado.git
Cloning into 'mikado'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
```

**Comment by gemygk** [comment]
Hi @desmodus1984 

Thank you for getting in touch.

Mikado is currently tested with Python 3.9 and 3.10, however it looks like you installed it using Python 3.12, which may be causing the issue you are seeing.

To make installation easier, I have created a DockerHub container which you can use by following the instructions here:
https://github.com/EI-CoreBioinformatics/mikado?tab=readme-ov-file#docker-installation

Alternatively, you can install Mikado via Singularity using the instructions here:
https://github.com/EI-CoreBioinformatics/mikado?tab=readme-ov-file#singularity-installation

Could you please try either of these approaches and let me know how it goes?

Regarding the Git SSH clone failure: this happens when GitHub does not detect an SSH key associated with your account/environment. You can instead clone the repository over HTTPS using:
```
git clone https://github.com/EI-CoreBioinformatics/mikado.git
```

Thanks,
Gemy

**Comment by desmodus1984** [comment]
Hi @gemygk 
I tried installing with conda and it failed with:
```
python3 setup.py bdist_wheel
```
It worked relatively well but then got an error:
"
creating build/lib.linux-x86_64-cpython-39/Mikado/configuration/scoring_files/HISTORIC
copying Mikado/configuration/scoring_files/HISTORIC/athaliana_scoring.yaml -> build/lib.linux-x86_64-cpython-39/Mikado/configuration/scoring_files/HISTORIC
copying Mikado/configuration/scoring_files/HISTORIC/celegans_scoring.yaml -> build/lib.linux-x86_64-cpython-39/Mikado/configuration/scoring_files/HISTORIC
copying Mikado/configuration/scoring_files/HISTORIC/dmelanogaster_scoring.yaml -> build/lib.linux-x86_64-cpython-39/Mikado/configuration/scoring_files/HISTORIC
copying Mikado/configuration/scoring_files/HISTORIC/hsapiens_scoring.yaml -> build/lib.linux-x86_64-cpython-39/Mikado/configuration/scoring_files/HISTORIC
copying Mikado/configuration/scoring_files/HISTORIC/human.yaml -> build/lib.linux-x86_64-cpython-39/Mikado/configuration/scoring_files/HISTORIC
copying Mikado/configuration/scoring_files/HISTORIC/insects.yaml -> build/lib.linux-x86_64-cpython-39/Mikado/configuration/scoring_files/HISTORIC
copying Mikado/configuration/scoring_files/HISTORIC/mammalian.yaml -> build/lib.linux-x86_64-cpython-39/Mikado/configuration/scoring_files/HISTORIC
copying Mikado/configuration/scoring_files/HISTORIC/plant.yaml -> build/lib.linux-x86_64-cpython-39/Mikado/configuration/scoring_files/HISTORIC
copying Mikado/configuration/scoring_files/HISTORIC/plants.yaml -> build/lib.linux-x86_64-cpython-39/Mikado/configuration/scoring_files/HISTORIC
copying Mikado/configuration/scoring_files/HISTORIC/scerevisiae.yaml -> build/lib.linux-x86_64-cpython-39/Mikado/configuration/scoring_files/HISTORIC
copying Mikado/configuration/scoring_files/HISTORIC/worm.yaml -> build/lib.linux-x86_64-cpython-39/Mikado/configuration/scoring_files/HISTORIC
copying Mikado/serializers/blast_serializer/aln_string_parser.cpp -> build/lib.linux-x86_64-cpython-39/Mikado/serializers/blast_serializer
copying Mikado/serializers/blast_serializer/aln_string_parser.pyx -> build/lib.linux-x86_64-cpython-39/Mikado/serializers/blast_serializer
copying Mikado/serializers/blast_serializer/btop_parser.cpp -> build/lib.linux-x86_64-cpython-39/Mikado/serializers/blast_serializer
copying Mikado/serializers/blast_serializer/btop_parser.pxd -> build/lib.linux-x86_64-cpython-39/Mikado/serializers/blast_serializer
copying Mikado/serializers/blast_serializer/btop_parser.pyx -> build/lib.linux-x86_64-cpython-39/Mikado/serializers/blast_serializer
running build_ext
**building 'Mikado.utilities.overlap' extension
creating build/temp.linux-x86_64-cpython-39/Mikado/utilities
gcc -pthread -B /data/common/juanpablo.aguilar/apps/Miniforge3/envs/mikado2/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /data/common/juanpablo.aguilar/apps/Miniforge3/envs/mikado2/include -fPIC -O2 -isystem /data/common/juanpablo.aguilar/apps/Miniforge3/envs/mikado2/include -fPIC -DNPY_NO_DEPRECATED_API=NPY_1_9_API_VERSION -I/data/common/juanpablo.aguilar/apps/Miniforge3/envs/mikado2/include/python3.9 -c Mikado/utilities/overlap.c -o build/temp.linux-x86_64-cpython-39/Mikado/utilities/overlap.o
error: command 'gcc' failed: No such file or directory**
"

**Comment by gemygk** [comment]
Hi @desmodus1984 

From the error log, it looks like GCC is not installed 
> error: command 'gcc' failed: No such file or directory

We need GCC for bdist_wheel (tested on gcc v5.2.0, v9.4.0 and v11.4.0)

Were you able to use the Docker or Singularity options I mentioned earlier [here](https://github.com/EI-CoreBioinformatics/mikado/issues/450#issuecomment-3748662556).  It would have made the installation much easier.

**Comment by desmodus1984** [comment]
I now tried 
```
mamba env create -f environment.yml --prefix /path/to/x86_64/envs/mikado_env
```
and it failed.
Error:
 Summary:

  Install: 296 packages

  Total download: 18MB

──────────────────────────────────────────────────────────────────────────────────────────────


Confirm changes: [Y/n] Y
critical libmamba filesystem error: cannot create directories: Permission denied [/path/to/x86_64/envs/mikado_env/conda-meta]

I wanted to create the file since the HPC doesn't have internet access and there seems that I need a file that it doesn't exist on the clone directory:
```
# 1. Create a Singularity definition file

$ cat mikado-2.3.5rc3.def
bootstrap: docker
from: gemygk/mikado:v2.3.5rc3
```

**Comment by desmodus1984** [comment]
> Hi [@desmodus1984](https://github.com/desmodus1984)
> 
> From the error log, it looks like GCC is not installed
> 
> > error: command 'gcc' failed: No such file or directory
> 
> We need GCC for bdist_wheel (tested on gcc v5.2.0, v9.4.0 and v11.4.0)
> 
> Were you able to use the Docker or Singularity options I mentioned earlier [here](https://github.com/EI-CoreBioinformatics/mikado/issues/450#issuecomment-3748662556). It would have made the installation much easier.

I have tried installing with Singularity and Docker and it failed:
#Docker
VERSION=2.3.5rc3
docker run gemygk/mikado:v${VERSION} mikado -h
docker: permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Head "http://%2Fvar%2Frun%2Fdocker.sock/_ping": dial unix /var/run/docker.sock: connect: permission denied

Run 'docker run --help' for more information

#Singularity
VERSION=2.3.5rc3
singularity exec docker://gemygk/mikado:v${VERSION} mikado -h
INFO:    Converting OCI blobs to SIF format
INFO:    Starting build...
INFO:    Fetching OCI image...
26.2MiB / 26.2MiB [==============================================================================================================] 100 % 23.4 MiB/s 0s
73.4MiB / 73.4MiB [==============================================================================================================] 100 % 23.4 MiB/s 0s
105.3MiB / 105.3MiB [============================================================================================================] 100 % 23.4 MiB/s 0s
82.8KiB / 82.8KiB [==============================================================================================================] 100 % 23.4 MiB/s 0s
1.2GiB / 1.2GiB [================================================================================================================] 100 % 23.4 MiB/s 0s
109.8MiB / 109.8MiB [============================================================================================================] 100 % 23.4 MiB/s 0s
INFO:    Extracting OCI image...
INFO:    Inserting Apptainer configuration...
INFO:    Creating SIF file...
[===========================================================================================================================================] 100 % 0s
ERROR  : Could not write info to setgroups: Permission denied
ERROR  : Error while waiting event for user namespace mappings: no event received
